Nine-Minds/alga-psa

docs/AI_coding_standards.md, server/src/app/msp/documents/page.tsx, server/src/components/documents/Documents.tsx, server/src/components/ui/DateRangePicker.tsx, server/src/config/menuConfig.ts, server/src/interfaces/document.interface.tsx, server/src/lib/actions/document-actions/documentActions.ts
Bringing public source tree up to current
=> New documents screen

server/src/components/settings/billing/TimePeriodSettings.tsx, server/src/lib/actions/time-period-settings-actions/timePeriodSettingsActions.ts, server/src/lib/actions/timePeriodsActions.ts, server/src/lib/utils/dateTimeUtils.ts, server/src/test/infrastructure/timePeriods.test.ts
Implements dynamic end-of-period handling for billing cycles, allowing more flexible time period configurations. Key changes include:
- Added END_OF_PERIOD constant (0) to indicate dynamic period endings
- Improved period boundary calculations for week/month/year frequencies
- Enhanced form UI with checkboxes for end-of-period selection
- Fixed date formatting consistency using UTC
- Updated tests to reflect new period boundary behavior
- Added validation for end-of-period settings
🐕 "There's no place like the end of a billing period!" - Toto, probably 🧙‍♀️✨
=> feat(billing): Add End-of-Period Support for Time Period Settings

server/src/components/contacts/Contacts.tsx, server/src/components/ui/DataTable.tsx
various datatables were creating infinite rendering loops because the react element ids that were created were unstable, leading to constant re-rendering. This resolves an issue with the datatable itself, and a specific instance in the contact table.
=> fix(datatable): fix cell id stability

server/src/components/billing-dashboard/ManualInvoices.tsx, server/src/lib/actions/manualInvoiceActions.ts
Add server action and UI integration for manual invoice creation. This includes:
- New manualInvoiceActions.ts with generateManualInvoice function
- Tax calculation and proper transaction recording
- Integration with existing invoice number generation
- Enable manual invoice generation in ManualInvoices component
- Handle proper tax and total calculations per line item
This allows users to create invoices manually with custom line items, while maintaining proper tax calculations and transaction records.
"If I only had a brain... I'd still need this manual invoice generator! Adds the ability to create invoices by hand, because sometimes even the smartest scarecrow needs to do things manually." -- Scarecrow
=> feat: implement manual invoice generation

server/src/components/companies/CompanyTaxRates.tsx, server/src/components/time-management/TimeEntryDialog.tsx, server/src/lib/actions/taxSettingsActions.ts, server/src/lib/actions/timeEntryActions.ts
- Auto-populate tax regions for tickets based on company defaults
- Fix tax region value to use name instead of ID in select options
- Correct tax rate calculation rounding
- Add comprehensive logging for tax rate fetching
- Remove unnecessary company tax rate filtering
"Under ze sea, ze taxes are better! Take it from me! Up on ze shore they work all day, calculating rates ze hard way, while we've got natural automation! 🦀 🐠 🐟"
=> feat: default time entry tax region dropdowns appropriately + fixes

server/migrations/20241223015715_create_system_interaction_types.cjs, server/migrations/20241223021233_update_interactions_type_constraint.cjs, server/src/components/interactions/InteractionsFeed.tsx, server/src/components/interactions/OverallInteractionsFeed.tsx, server/src/components/interactions/QuickAddInteraction.tsx, server/src/components/settings/general/InteractionTypeSettings.tsx, server/src/components/ui/CustomSelect.tsx, server/src/interfaces/interaction.interfaces.ts, server/src/lib/actions/interactionTypeActions.ts, server/src/lib/models/interactions.ts, server/src/lib/utils/getSecret.ts
Add support for system-wide interaction types with the following changes:
- Create system_interaction_types table with default types (Call, Email, Meeting, Note)
- Add system_type_id reference to tenant-specific interaction_types
- Update UI to distinguish between system and custom types
- Implement validation triggers to prevent modification of system types
- Update queries to handle both system and tenant-specific types
- Add inheritance support for custom types based on system types
This change provides a standardized set of core interaction types while
maintaining flexibility for tenant-specific customization.
"Oh dear! Oh dear! I shall be too late for a very important meeting... though I must say, the system types will make scheduling much more organized! checks pocket watch …
=> feat(interactions): implement system-wide interaction types 

docs/scheduling.md, server/migrations/20250103172553_add_adhoc_schedule_entries.cjs, server/src/components/time-management/EntryPopup.tsx, server/src/components/time-management/ScheduleCalendar.tsx, server/src/components/time-management/SelectedWorkItem.tsx, server/src/components/time-management/WorkItemPicker.tsx, server/src/interfaces/schedule.interfaces.ts, server/src/interfaces/workItem.interfaces.ts, server/src/lib/actions/scheduleActions.ts, server/src/lib/models/scheduleEntry.ts, server/src/lib/schemas/scheduleSchemas.ts
Made work_item_id nullable in the database schema
Added ad_hoc as a valid work_item_type
Updated UI components to handle ad-hoc entries
Enhanced validation logic for ad-hoc entries
Improved logging and error handling
"Curiouser and curiouser! 🐇 Now you can schedule ad-hoc entries, just like the White Rabbit's ever-changing appointments. Time is a funny thing, isn't it? ⏳"
=> ✨ Add support for ad-hoc schedule entries 🕒

server/migrations/20250103224828_remove_wbs_code_unique_constraint.cjs, server/src/components/projects/KanbanBoard.tsx, server/src/components/projects/ProjectDetail.tsx, server/src/components/projects/StatusColumn.tsx, server/src/lib/actions/projectActions.ts
This update introduces the ability to reorder tasks within status columns using drag-and-drop functionality. Tasks now maintain their order through WBS codes, with visual indicators showing drop positions. A database migration removes the unique constraint on WBS codes to support this feature.
Key changes:
- Add reorderTasksInStatus server action
- Implement drag-and-drop reordering UI with visual guides
- Remove unique constraint on WBS codes
- Sort tasks by WBS code in status columns
🧙‍♀️ "Dorothy would be proud - we're not in static task orders anymore! Now our tasks can dance down the yellow brick road in any order they choose ✨"
=> feat: Enable drag-and-drop task reordering within status columns 🔄

server/migrations/20250118150946_add_is_manual_to_invoices.cjs, server/src/components/billing-dashboard/Invoices.tsx, server/src/components/billing-dashboard/ManualInvoices.tsx, server/src/interfaces/invoice.interfaces.ts, server/src/lib/actions/manualInvoiceActions.ts, server/src/lib/models/invoice.ts
This commit adds functionality to edit manually created invoices, including:
- Added `is_manual` flag to invoices table to identify manual invoices
- Added UI controls to edit manual invoices in the billing dashboard
- Implemented backend support for updating existing manual invoices
- Fixed currency handling by storing amounts in cents consistently
- Added proper type definitions and interfaces for manual invoices
- Improved error handling and validation for invoice operations
This change allows users to modify previously created manual invoices while maintaining proper audit trails and data consistency.
Because 'oops' shouldn't be a permanent state in your billing system 🎭
=> feat: Add support for editing manual invoices

server/migrations/20250118210219_add_manual_invoice_items.cjs, server/src/components/billing-dashboard/Invoices.tsx, server/src/components/billing-dashboard/LineItem.tsx, server/src/components/billing-dashboard/ManualInvoices.tsx, server/src/interfaces/invoice.interfaces.ts, server/src/lib/actions/invoiceActions.ts, server/src/lib/actions/manualInvoiceActions.ts, server/src/lib/actions/taxSettingsActions.ts, server/src/lib/billing/billingEngine.ts, server/src/lib/models/invoice.ts, server/src/utils/sampleInvoiceData.ts
This commit adds comprehensive support for managing manual line items on both automated and manual invoices, including:
- New database migration to add manual item tracking fields
- Updated UI to support adding/editing/removing manual items
- Improved invoice recalculation logic for accurate tax handling
- Better handling of monetary values consistently in cents
- Enhanced logging for debugging and monitoring
- Fixed various rounding and calculation issues
Key Features:
- Users can now add manual items to any invoice type
- Support for removing and restoring manual items
- Proper audit trail with created_by/updated_by tracking
- Automated tax recalculation when items change
- Improved monetary value consistency across the system
Breaking Changes:
- All monetary values now stored and …
=> feat: add support for manual line items on invoices

server/migrations/20250119202505_add_discount_fields_to_invoice_items.cjs, server/migrations/20250119232202_add_discount_percentage_to_invoice_items.cjs, server/src/components/billing-dashboard/LineItem.tsx, server/src/components/billing-dashboard/ManualInvoices.tsx, server/src/interfaces/invoice.interfaces.ts, server/src/lib/actions/invoiceActions.ts, server/src/lib/actions/manualInvoiceActions.ts, server/src/lib/billing/billingEngine.ts, server/src/lib/models/invoice.ts
This change enables users to add both percentage and fixed-amount discounts to invoices, either applying to specific line items or the entire invoice.
Key changes:
- Add discount fields to invoice_items table
- Support both percentage and fixed-amount discounts
- Update billing engine to handle discount calculations
- Add UI controls for adding and managing discounts
- Preserve original percentages for percentage-based discounts
- Ensure proper tax handling (discounts are not taxed)
Technical details:
- Added is_discount, discount_type, and discount_percentage fields
- Added applies_to_item_id for item-specific discounts
- Updated BillingEngine to process discounts after regular items
- Enhanced recalculation logic to handle percentage discounts
👑 "Off with their prices!" declared the …
=> feat: Add support for invoice discounts

.gitignore, server/src/components/billing-dashboard/TemplateRenderer.tsx, server/src/services/pdf-generation.service.ts
feat: add PDF generation for invoices
- Add PDF generation service using Puppeteer
- Implement server-side template rendering for PDF export
- Add PDF download option to invoice actions menu
- Add metadata support to storage service
- Update TemplateRenderer to support server-side rendering
- Add getCurrentUser integration for storage operations
The changes enable PDF generation and download for invoices using the existing template system, rendered server-side with Puppeteer. Includes necessary storage service updates and improved error handling.
wip
fix: invoice rendering loops
=> fix: invoice rendering loops

server/migrations/20250130181441_add_invoice_template_selection.cjs, server/src/components/billing-dashboard/InvoiceTemplates.tsx, server/src/components/companies/BillingConfigForm.tsx, server/src/components/companies/BillingConfiguration.tsx, server/src/interfaces/company.interfaces.tsx, server/src/interfaces/invoice.interfaces.ts, server/src/lib/actions/invoiceActions.ts, server/src/services/pdf-generation.service.ts
Adds ability to select and manage invoice templates per company with default template support.
Key changes:
- Added invoice_template_id to companies table with foreign key constraint
- Created unique index to ensure only one default template per tenant
- Added UI for setting default templates and selecting company-specific templates
- Enhanced PDF generation to respect company template preferences
- Updated billing configuration to include template selection
- Added fallback logic: company template -> default template -> first available
The changes improve invoice customization by allowing companies to use specific templates while maintaining a default template system-wide.
"Pay no attention to that default template behind the curtain! Each company can now choose their own Great and …
=> feat: Add company-specific invoice template selection

ee/server/src/components/chat/Chat.tsx, ee/server/src/components/flow/DnDFlow.tsx, ee/server/src/services/flow/types/nodes.ts, ee/server/tsconfig.json, eslint.config.js, server/src/components/companies/CompanyPicker.tsx, server/tsconfig.json, tsconfig.base.json
- Create shared base TypeScript config (tsconfig.base.json)
- Update server and ee/server TypeScript configs to extend base
- Standardize import paths using @/ and @ee/ aliases
- Clean up unnecessary TypeScript config options
- Remove unused import in CompanyPicker
- Fix tsconfigRootDir in ESLint config to use process.cwd()
=> refactor: improve TypeScript configuration and import paths

docs/setup_guide.md
- Replace source-build instructions with prebuilt image workflow
- Remove detailed database description as it's not relevant to the setup guide
- Simplify Docker Compose commands to use prebuilt configurations
- Remove manual migration/seeding steps that are now automated
- Update upgrade process to use docker compose pull workflow
This change reflects the move to a more streamlined deployment process using prebuilt Docker images instead of source builds.
=> docs: simplify setup guide for prebuilt deployment

server/src/components/settings/general/TicketNumberingSettings.tsx, server/src/components/settings/general/TicketingSettings.tsx, server/src/components/settings/general/UserDetails.tsx, server/src/components/settings/policy/PermissionManagement.tsx, server/src/lib/actions/ticket-number-actions/ticketNumberActions.ts
Implemented a comprehensive ticket numbering system that allows administrators to:
- Set and modify ticket number prefixes
- Configure initial values and last used numbers
- Preview next ticket number format
- Added role-based access controls with confirmation dialogs
- Integrated with existing tenant-aware database operations
Fixed admin access control to use role_name instead of role_id "Follow the white rabbit down the ticket numbering hole... but only if you have the admin credentials!" 🌌🔢
=> Add ticket numbering configuration UI with admin safeguards 🐇🎟️

server/migrations/20250220164843_add_padding_to_next_number.cjs, server/migrations/20250220165247_update_generate_next_number_function.cjs, server/src/components/settings/general/NumberingSettings.tsx, server/src/components/settings/general/SettingsPage.tsx, server/src/components/settings/general/TicketingSettings.tsx, server/src/lib/actions/number-actions/numberingActions.ts, server/src/lib/services/numberingService.ts
Adds support for configurable number padding and enhances number generation system:
- Add padding_length column to next_number table with default of 6 digits
- Update generate_next_number function to support padded numbers
- Create reusable NumberingSettings component for both tickets and invoices
- Add number management UI with preview, validation, and admin controls
- Add server actions for managing number settings
- Enhance NumberingService to handle multiple entity types
- Deprecate getNextTicketNumber in favor of generic getNextNumber method
This change allows administrators to configure:
- Number prefixes (e.g. TK-, INV-)
- Padding length (1-10 digits)
- Initial and current number values
The system now generates properly formatted numbers like "TK-000123" or "INV-000456" with …
=> feat: Add configurable number padding and improve number generation

server/migrations/20250222004732_create_zero_dollar_invoice_settings_tables.cjs, server/src/components/companies/BillingConfiguration.tsx, server/src/components/companies/CompanyZeroDollarInvoiceSettings.tsx, server/src/components/settings/billing/ZeroDollarInvoiceSettings.tsx, server/src/components/settings/general/SettingsPage.tsx, server/src/lib/actions/billingSettingsActions.ts, server/src/lib/actions/invoiceActions.ts, server/src/test/infrastructure/invoiceNumberGeneration_part1.test.ts
This commit adds functionality to manage how zero-dollar invoices are handled:
- Adds migration for default_billing_settings and company_billing_settings tables
- Implements company-specific and default tenant-wide settings
- Adds UI components for configuring settings at both levels
- Introduces options to:
- Create zero-dollar invoices as draft or finalized
- Suppress zero-dollar invoices entirely
- Updates invoice generation logic to respect these settings
- Includes UI components for both global and company-specific settings
- Adds null safety checks in invoice tests
The feature allows fine-grained control over zero-dollar invoice behavior at both the system and company level, with company settings taking precedence over defaults.
🎩 "Would you tell me, please, which way I should …
=> feat: Add zero-dollar invoice handling settings and configuration

server/migrations/20250223174203_add_is_taxable_to_invoice_items.cjs, server/src/interfaces/billing.interfaces.ts, server/src/lib/actions/invoiceActions.ts, server/src/lib/billing/billingEngine.ts, server/src/lib/services/invoiceService.ts, server/src/lib/services/taxService.ts, server/src/test/infrastructure/billingInvoiceGeneration.test.ts
This change adds granular tax control at the invoice item level, improving tax calculation accuracy:
- Add is_taxable column to invoice_items table with migration
- Copy existing is_taxable values from service_catalog during migration
- Update billing engine and invoice services to respect is_taxable flag
- Modify tax calculation logic to handle mixed taxable/non-taxable items
- Update tax distribution to only apply to taxable items with positive amounts
- Add tests to verify mixed taxable/non-taxable item scenarios
This change allows for more flexible tax handling while maintaining backward compatibility by defaulting is_taxable to true.
🌹 "We're painting the tax rates RED!" screamed the Card Guards. "Unless they're marked non-taxable, in which case we're painting them transparent. …
=> feat: Add is_taxable flag to invoice items

server/migrations/202502232002_add_tax_rate_exclusion_constraint.cjs, server/src/components/billing-dashboard/TaxRates.tsx, server/src/lib/actions/taxRateActions.ts, server/src/lib/services/taxService.ts, server/src/test/infrastructure/taxRateChanges.test.ts
This commit introduces several improvements to tax rate management:
- Add database constraint to prevent overlapping tax rates for the same tenant/region
- Implement validation logic in TaxService to check for date range overlaps
- Enhance form validation and error handling in the UI
- Improve date formatting and input handling
- Add proper type safety and error messages
- Clean up form field IDs and UI components
- Fix update tax rate function to properly handle null end dates
The changes ensure that tax rates for a given region cannot overlap in time, preventing potential conflicts in tax calculations.
🐶 Toto, I've a feeling these tax rates aren't overlapping anymore
=> feat: Add date range validation for tax rates

server/src/lib/models/interactions.ts, server/src/lib/models/scheduleEntry.ts
Remove tenant check from system_interaction_types join (global table) Explicitly scope all tenant WHERE clauses to specific tables Prevent accidental cross-tenant data exposure through ambiguous joins The White Rabbit insists all tenants stay in their own tea parties 🐇🎩 No more wandering down wrong rabbit holes when managing schedules!
=> Fix tenant isolation in schedule entry queries

server/src/lib/actions/manualInvoiceActions.ts, server/src/lib/billing/billingEngine.ts, server/src/test/infrastructure/billingInvoiceGeneration_tax.test.ts, server/src/test/infrastructure/creditApplication.test.ts, server/src/test/infrastructure/manualInvoice.test.ts
Convert date strings to Temporal objects properly with new toPlainDate util. Convert floating-point money values to integers for consistent calculations. Add regional tax support to handle items from different tax jurisdictions. Add comprehensive tests for credit application and manual invoice updates.
"🃏 'Begin at the beginning,' said the King, 'and format until you come to the end: then parse.'"
=> fix: ensure proper tax region handling and format conversions

server/migrations/20250225165701_change_invoice_items_quantity_to_decimal.cjs, server/src/lib/actions/manualInvoiceActions.ts, server/src/test/infrastructure/billingInvoiceGeneration_subtotal.test.ts, server/src/test/infrastructure/manualInvoice.test.ts
Change invoice_items.quantity from bigInteger to decimal(10,2) to allow storing fractional quantities instead of truncating to integers. This enables more flexible billing for services measured in partial units.
- Add migration to convert columns in invoice_items and usage_tracking tables
- Update manual invoice actions to handle fractional quantities correctly
- Fix int parsing in invoice generation methods
- Add tests verifying proper rounding behavior with fractional quantities
- Add comprehensive tests for manual invoice adjustments
=> feat: support fractional quantities in invoices

server/src/components/tickets/TicketDetails.tsx, server/src/lib/actions/ticket-actions/ticketActions.ts, server/src/lib/eventBus/consumers/emailNotificationConsumer.ts
This commit improves the ticket assignment process by properly managing ticket resources when the assigned agent changes. The changes:
- Automatically refresh additional resources after assignment change in UI
- Implement transaction-based assignment change in ticket actions API
- Fix field name references in email notification consumer (assigned_user_id → assigned_to)
This resolves issues where ticket resources could become invalid or out of sync when changing the ticket assignee.
=> fix(tickets): update resource assignments when ticket assignee changes

server/src/components/schedule/EntryPopup.tsx, server/src/components/schedule/ScheduleCalendar.tsx, server/src/lib/actions/scheduleActions.ts, server/src/lib/actions/workItemActions.ts
Add a "Details" button to the Entry Popup that opens the WorkItemDrawer for tickets and project tasks, replacing the previous behavior where users had to click on the event title. This improves discoverability and provides a more consistent way to access work item details.
Additional changes:
- Fix groupBy query in getWorkItemById to include additional_user_ids
- Ensure work_item_type is preserved when updating schedule entries
- Verify work_item_type is specified for entries with a work_item_id
=> feat(schedule): add Details button to view work item information

server/migrations/20250318104900_add_billing_plan_id_to_time_entries.cjs, server/migrations/20250318105000_add_billing_plan_id_to_usage_tracking.cjs, server/src/components/billing-dashboard/BillingPlans.tsx, server/src/components/billing-dashboard/UsageTracking.tsx, server/src/components/time-management/time-entry/time-sheet/TimeEntryDialog.tsx, server/src/components/time-management/time-entry/time-sheet/TimeEntryEditForm.tsx, server/src/components/time-management/time-entry/time-sheet/TimeEntryProvider.tsx, server/src/components/time-management/time-entry/time-sheet/types.ts, server/src/interfaces/timeEntry.interfaces.ts, server/src/interfaces/usage.interfaces.ts, server/src/lib/actions/timeEntryActions.ts, server/src/lib/actions/usageActions.ts, server/src/lib/billing/billingEngine.ts, server/src/lib/utils/planDisambiguation.ts, server/src/test/unit/billingEngine.test.ts, server/src/test/unit/billingPlanSelection.test.ts, server/src/test/unit/planDisambiguation.test.ts, server/src/test/unit/timeEntryBillingPlanSelection.test.tsx
- Added `billing_plan_id` to `time_entries` and `usage_tracking` tables via database migrations
- Updated `ITimeEntry` and `IUsageRecord` TypeScript interfaces to include `billing_plan_id`
- Implemented default plan selection algorithms for time entries and usage records
- Updated time entry and usage tracking APIs to handle billing plan assignments
- Modified billing engine to filter charges by billing plan in `calculateTimeBasedCharges` and `calculateUsageBasedCharges`
- Added fallback mechanisms for existing entries without billing plan assignments
- Implemented validation logic and warnings for conflicting service plans
- Created unit tests for updated billing engine and plan disambiguation logic
- Designed and implemented plan selection components for time entry and usage tracking …
=> feat: Implement Multiple Billing Plan Disambiguation system

server/src/components/documents/Documents.tsx, server/src/components/schedule/EntryPopup.tsx, server/src/components/ui/Drawer.tsx, server/src/components/user-activities/ActivityDetailsDrawer.tsx, server/src/context/DrawerContext.tsx
- Added conditional rendering of close buttons based on `isInDrawer` prop to prevent duplicate close buttons in nested drawers
- Updated Drawer component to use Lucide's X icon instead of Radix UI's Cross2Icon for consistency
- Modified Documents, EntryPopup, and ActivityDetailsDrawer components to properly handle drawer context
- Simplified close button logic in DrawerContext to only show for root-level drawers
These changes create a more consistent drawer experience and prevent UI clutter from duplicate close buttons. The Mad Hatter would approve of this much cleaner tea party setup! 🎩☕
=> Improve drawer component consistency and behavior

server/src/components/billing-dashboard/UnitOfMeasureInput.tsx, server/src/components/billing-dashboard/billing-plans/BillingPlanServiceForm.tsx, server/src/components/billing-dashboard/billing-plans/GenericPlanServicesList.tsx, server/src/components/billing-dashboard/billing-plans/UsagePlanConfiguration.tsx, server/src/lib/actions/planServiceActions.ts, server/src/lib/actions/planServiceConfigurationActions.ts, server/src/lib/models/planServiceUsageConfig.ts, server/src/lib/models/service.ts, server/src/lib/services/planServiceConfigurationService.ts
This commit addresses several bugs and usability issues within the usage-based plan configuration interface, focusing on making service configuration more intuitive and ensuring data persistence.
- **Enable Row Click for Service Configuration:** Allows users to configure services within a usage-based plan by clicking directly on the service row in `GenericPlanServicesList`, providing an alternative to the actions menu.
- **Replace Description Text with Tooltips:** Improves UI clarity in `UsagePlanConfiguration` by replacing descriptive text below input fields (Rate per unit, Unit of measure, Minimum billable units) with info icons and tooltips, reducing visual clutter.
- **Fix Usage-Based Plan and Service Configuration Saving:**
- Corrects the incomplete plan-level save logic in …
=> feat(usage-plans): Enhance configuration UX and fix saving logic

docs/billing.md, server/migrations/20250328030000_add_base_rate_to_plan_service_usage_config.cjs, server/src/components/billing-dashboard/billing-plans/GenericPlanServicesList.tsx, server/src/components/billing-dashboard/billing-plans/ServiceTierEditor.tsx, server/src/components/billing-dashboard/billing-plans/ServiceUsageConfigForm.tsx, server/src/components/billing-dashboard/billing-plans/UsagePlanConfiguration.tsx, server/src/interfaces/index.ts, server/src/interfaces/planServiceConfiguration.interfaces.ts, server/src/lib/actions/planServiceConfigurationActions.ts
This commit introduces the ability to configure tiered pricing specifically for individual services within a usage plan, moving away from plan-level tiered pricing. This provides greater flexibility in defining billing structures.
Key changes include:
**Database:**
- Added a `base_rate` column (numeric, nullable) to the `plan_service_usage_config` table via migration to support non-tiered pricing per service.
**Backend:**
- Created `getPlanServiceConfiguration` action to fetch detailed configuration (base rate, tiers, etc.) for a specific service within a plan.
- Created `upsertPlanServiceConfiguration` action to save service-level configuration, handling base rate and tiers within a database transaction.
- Implemented server-side validation for rates, usage limits, and tier structures …
=> feat(billing): Implement service-level tiered pricing for usage plans

package-lock.json, package.json, server/package.json, server/src/components/billing-dashboard/billing-plans/BucketPlanConfiguration.tsx, server/src/components/billing-dashboard/billing-plans/GenericPlanServicesList.tsx, server/src/components/billing-dashboard/billing-plans/ServiceBucketConfigForm.tsx, server/src/lib/actions/planServiceConfigurationActions.ts, server/src/lib/services/planServiceConfigurationService.ts
Refactors the Bucket Plan configuration UI to use an accordion, allowing individual configuration (total units, overage, rollover) for each service within the plan. Replaces the previous plan-wide settings model.
Includes fixes for dynamic unit display, tooltip usage, and filtering applicable services.
=> refactor(billing/bucket-plan): Implement per-service configuration

package-lock.json, server/migrations/20250318200000_create_plan_service_configuration_tables.cjs, server/migrations/20250327144330_rename_service_categories_to_ticket_categories.cjs, server/migrations/20250331164116_alter_plan_service_configuration_pk.cjs, server/migrations/20250331164117_create_plan_service_hourly_configs_table.cjs, server/migrations/20250331181202_add_plan_wide_hourly_settings_to_billing_plans.cjs, server/migrations/20250331190508_fix_user_type_rates_fk.cjs, server/package.json, server/src/components/billing-dashboard/billing-plans/HourlyPlanConfiguration.tsx, server/src/components/billing-dashboard/billing-plans/ServiceHourlyConfigForm.tsx, server/src/components/companies/BillingConfigForm.tsx, server/src/interfaces/billing.interfaces.ts, server/src/interfaces/planServiceConfiguration.interfaces.ts, server/src/lib/actions/billingPlanAction.ts, server/src/lib/actions/planServiceActions.ts, server/src/lib/actions/planServiceConfigurationActions.ts, server/src/lib/billing/billingEngine.ts, server/src/lib/models/planServiceHourlyConfig.ts, server/src/lib/services/planServiceConfigurationService.ts
This commit introduces significant changes to the Hourly Plan configuration:
-   **Database Migration:**
-   Modifies the `plan_service_configuration` table to use a composite primary key (`tenant`, `config_id`).
-   Creates a new table `plan_service_hourly_configs` to store hourly-specific settings.
-   Adds plan-wide hourly settings (overtime, after-hours) to the `billing_plans` table.
-   Fixes the foreign key in `user_type_rates` to correctly reference `plan_service_hourly_configs`.
-   **Frontend Refactor:**
-   Replaces plan-wide hourly settings with service-specific configurations.
-   Implements a new `ServiceHourlyConfigForm` component to manage hourly rates and user type rates for individual services.
-   Uses `lodash/isEqual` for deep object comparison to detect changes.
- …
=> feat: Refactor Hourly Plan Configuration and Service Settings

server/migrations/20250331164116_alter_plan_service_configuration_pk.cjs, server/migrations/20250331190508_fix_user_type_rates_fk.cjs, server/src/components/billing-dashboard/UsageTracking.tsx, server/src/lib/actions/timeEntryActions.ts, server/src/lib/utils/planDisambiguation.ts
- Fix database migration issues with foreign key constraints in plan service configurations
- Update service queries to use billing_method instead of service_type for backwards compatibility
- Filter usage tracking service selection to only show per_unit services
=> fix(billing): repair database migration issues with foreign keys and service selection

server/migrations/20250405231703_populate_enforce_billing_method_on_types.cjs, server/migrations/20250405231739_enforce_service_billing_method.cjs, server/src/components/billing-dashboard/BillingPlanDialog.tsx, server/src/components/billing-dashboard/BillingPlans.tsx, server/src/components/billing-dashboard/FixedPlanServicesList.tsx, server/src/components/billing-dashboard/QuickAddService.tsx, server/src/components/billing-dashboard/ServiceCatalogManager.tsx, server/src/components/billing-dashboard/ServiceForm.tsx, server/src/components/billing-dashboard/billing-plans/BillingPlanServiceForm.tsx, server/src/components/billing-dashboard/billing-plans/BillingPlansOverview.tsx, server/src/components/billing-dashboard/billing-plans/FixedPlanConfiguration.tsx, server/src/components/billing-dashboard/billing-plans/GenericPlanServicesList.tsx, server/src/components/billing-dashboard/service-config/ServiceConfigurationPanel.tsx, server/src/components/billing-dashboard/service-config/ServiceSelectionDialog.tsx, server/src/components/companies/BillingConfiguration.tsx, server/src/components/companies/CompanyServiceOverlapMatrix.tsx, server/src/components/settings/billing/ServiceTypeSettings.tsx, server/src/interfaces/billing.interfaces.ts, server/src/lib/actions/planServiceActions.ts, server/src/lib/actions/report-actions/getHoursByServiceType.ts, server/src/lib/actions/serviceActions.ts, server/src/lib/actions/timeEntryActions.ts, server/src/lib/models/service.ts, server/src/lib/models/serviceType.ts, server/src/lib/utils/planDisambiguation.ts
- Added migrations to populate and enforce billing methods on service types:
- `20250405231703_populate_enforce_billing_method_on_types.cjs`:
- Populates billing_method on standard_service_types
- Adds CHECK constraints for billing_method values
- Migrates data to service_types table
- `20250405231739_enforce_service_billing_method.cjs`:
- Restructures service_catalog to use separate FKs for standard/custom types
- Enforces billing method constraints
- Updated UI components to handle new billing method requirements:
- FixedPlanServicesList.tsx: Filters services by billing method
- QuickAddService.tsx: Supports standard/custom type selection
- ServiceCatalogManager.tsx: Handles new type ID structure
- ServiceForm.tsx: Updated for new type selection logic
- Enhanced service models and …
=> feat(billing): enforce service type billing methods and migrate data

server/src/components/technician-dispatch/TechnicianDispatchDashboard.tsx, server/src/components/time-management/time-entry/time-sheet/WorkItemPicker.tsx, server/src/lib/actions/workItemActions.ts
Removed type filtering from TechnicianDispatchDashboard since it only handles tickets now Added context parameter to differentiate dispatch vs picker search modes Dispatch mode now only searches tickets while picker maintains both ticket and project task search Updated description field to use attributes.description instead of url Improved query union handling with explicit context-based filtering
"Off with their types!" cried the Red Queen, as the dispatch dashboard shed its project task baggage like a caterpillar shedding its cocoon, emerging as a lean, ticket-focused butterfly. 🎟️🐛🦋
=> Refactor work item search and filtering

server/migrations/20250515104157_add_private_flag_to_schedule_entries.cjs, server/src/components/schedule/EntryPopup.tsx, server/src/components/technician-dispatch/TechnicianDispatchDashboard.tsx, server/src/components/technician-dispatch/WeeklyScheduleEvent.tsx, server/src/components/technician-dispatch/WeeklyTechnicianScheduleGrid.tsx, server/src/components/tickets/ticket/AgentScheduleDrawer.tsx, server/src/components/ui/DateTimePicker.tsx, server/src/interfaces/schedule.interfaces.ts, server/src/lib/actions/scheduleActions.ts, server/src/lib/models/scheduleEntry.ts
- Added is_private flag to schedule entries with database migration
- Implemented private entry visibility rules across all schedule components
- Restricted editing/deletion of private entries to creators only
- Show "Busy" placeholder for private entries viewed by others
- Added private toggle switch in EntryPopup (visible only for self-assigned entries)
- Updated schedule actions to enforce private entry permissions
Impacts:
- Affects all schedule views and entry management
- Changes IScheduleEntry interface and database schema
- Modifies permission checks in scheduleActions
- Updates display logic across multiple components
"Private parties require private calendars," declared the Cheshire Cat, vanishing all but the approved guests from view 🎩🐱👤
=> Added private scheduling functionality with visibility controls

server/src/components/billing-dashboard/EditPlanServiceQuantityDialog.tsx, server/src/components/billing-dashboard/FixedPlanServicesList.tsx, server/src/components/billing-dashboard/billing-plans/FixedPlanConfiguration.tsx, server/src/components/billing-dashboard/billing-plans/PlanTypeRouter.tsx, server/src/components/ui/EntityAvatar.tsx, server/src/components/ui/EntityImageUpload.tsx, server/src/components/user-activities/ActivityDetailViewerDrawer.tsx
Replaced various Lucide Loader2 spinners with centralized LoadingIndicator and Spinner components Updated loading states in billing dashboard components (EditPlanServiceQuantityDialog, FixedPlanServicesList, PlanTypeRouter) Standardized loading indicators in UI components (EntityAvatar, EntityImageUpload) Improved ActivityDetailViewerDrawer loading state with new Spinner component Impacts:
More consistent loading UI across the application
Easier to modify loading indicators globally
Reduced direct dependency on Lucide icons
There's a couple that slipped through my thrift last time, but most spinners now dance to the same tune. 🎩♫🌀
=> Refactor loading indicators to use consistent UI components

.github/workflows/publish-package.yaml
- Added push/create triggers for version tags (v*.*.*)
- Modified publish job condition to handle multiple event types
- Implemented dynamic Docker tag determination based on event type
- Consolidated tag output into single step
Impact: More flexible publishing options for both CI and manual version releases.
Like a mad scientist's experiment, these tags shall now multiply uncontrollably! May the version gods have mercy on our CI pipeline! 🧪🔖🤪
=> Add version tag triggers and dynamic Docker tagging to publish workflow

server/src/components/companies/Companies.tsx, server/src/components/companies/CompaniesGrid.tsx, server/src/components/companies/CompaniesList.tsx, server/src/lib/actions/company-actions/companyActions.ts, server/src/lib/actions/ticket-actions/optimizedTicketActions.ts, server/src/lib/models/document.tsx, server/src/lib/utils/avatarUtils.ts
- Added getAllCompaniesPaginated endpoint with filtering and pagination support
- Modified Companies component to use server-side pagination
- Updated CompaniesGrid and CompaniesList to support pagination props
- Implemented batch logo loading with getCompanyLogoUrlsBatch
- Optimized document queries by splitting joins into separate queries
- Added debug logging for development environment only
Impacts:
- Reduces database load by implementing server-side pagination
- Improves performance by batch loading company logos
- More efficient document queries by avoiding complex joins
- Better scalability for large company lists
"Down the rabbit hole we go, where companies multiply like mad hatters and logos appear in batches like a deck of cards dealt by the Cheshire Cat!" 🐇🎩🃏
=> Implemented server-side pagination and batch logo loading for companies

helm/templates/dev-env/ai-automation/nginx-configmap.yaml
Fixes the VNC redirect issue where accessing `/vnc` would incorrectly redirect to port 8080 instead of preserving the original port.
- Added nginx maps to properly handle `X-Forwarded-Host` and `X-Forwarded-Proto` headers
- Updated the `/vnc` redirect to use `$proxy_scheme://$best_host/vnc/` instead of a relative redirect
- Ensures port preservation when redirecting from `/vnc` to `/vnc/`
- Access VNC via `/vnc` endpoint on a non-8080 port (e.g., `localhost:30007/vnc`)
- Verify the redirect preserves the correct port and protocol
- Confirm VNC interface loads correctly after redirect
This fixes VNC access in development environments where the AI automation service is exposed on ports other than 8080.
=> Fix VNC redirect port preservation in AI automation nginx proxy

cli/dev-env.nu
Fix parsing error in nushell CLI where parentheses around URL were being interpreted as a command to execute.
- Escape parentheses in string interpolation around `http://code-server:3000` URL
- Prevents nushell from treating the URL as an executable command
=> Fix nushell parsing error in dev-env-force-cleanup

helm/values-dev-env.yaml
• Increase NextAuth session expiry from 30 seconds to 24 hours in development environments
• Prevents frequent re-authentication interruptions during development work
=> Fix session timeout in dev environments

.github/workflows/e2e-fresh-install-tests.yaml
Fixes race conditions in the e2e-fresh-install-tests workflow by implementing a staged service startup approach.
The current workflow starts all Docker Compose services simultaneously, causing race conditions where:
- Application services try to connect to the database before migrations complete
- Services fail to start due to missing database schemas
- Tests fail intermittently due to timing issues
Implemented a 5-stage startup process:
- Start `postgres` and `redis` first
- These are the core dependencies for all other services
- Wait for postgres to be ready using `pg_isready`
- Wait for redis to respond to ping (with auth fallback)
- Proper timeout and error handling
- Start `pgbouncer` and `setup` services
- These depend on postgres being ready
- Wait for setup service to complete …
=> Fix race conditions in e2e fresh install tests with staged service startup

server/src/lib/document-handlers/DocumentHandlerRegistry.ts, server/src/lib/document-handlers/VideoDocumentHandler.ts
- ✅ Created VideoDocumentHandler that doesn't need Chrome  
- ✅ Registered it in the handler registry before the generic handler
- ✅ Videos no longer fall through to the Puppeteer-based generic handler
=> separate handler for video preview

helm/templates/jobs.yaml, helm/templates/migration-hook.yaml, helm/values.yaml
- Add `runMigrations` flag to Helm values.yaml to control database migration execution
- Update jobs.yaml to respect runMigrations flag alongside existing devEnv check
- Wrap migration-hook.yaml with runMigrations conditional to allow selective skipping
- Enables deployment flexibility by allowing migrations to be disabled when needed
=> feat: Add configurable migration control to Helm charts

helm/templates/dev-env/code-server/pvc.yaml, helm/templates/local-storage-pvc.yaml, helm/templates/postgres/pvc.yaml, helm/templates/redis/pvc.yaml, helm/templates/storage-pvc.yaml
- Add Helm lookup logic to preserve existing volumeName in all PVC templates
- Prevents "spec is immutable" errors during Helm upgrades when PVCs are already bound
- Applied to storage, redis, postgres, local-storage, and dev-env code-server PVCs
Helm was attempting to modify the volumeName field in existing PersistentVolumeClaims from bound volume names to empty strings, which is forbidden since volumeName is immutable after PVC creation.
Added lookup logic to each PVC template that:
1. Checks if the PVC already exists using Helm's lookup function
2. Preserves the existing volumeName if it was previously set by Kubernetes
3. Allows new PVCs to be created without volumeName (letting Kubernetes assign it dynamically)
=> fix: preserve volumeName in PVC templates to avoid immutability errors

server/migrations/20250707120000_drop_deprecated_company_fields.cjs
- Fixed CitusDB distributed table JOIN error in company migration
- Replaced problematic LEFT JOIN with tenant-based iteration
- Maintains same functionality while ensuring CitusDB compatibility
- Loop through each tenant individually to ensure queries operate within single shards
- Use parameterized queries to prevent SQL injection  
- Avoids "complex joins are only supported when all distributed tables are co-located" error
=> fix: resolve CitusDB distributed table JOIN issue in company migration

server/src/components/dashboard/Dashboard.tsx, server/src/config/menuConfig.ts
- Changed "Dashboard" menu item to "Home" with Home icon 🏠
- Moved BarChart3 icon to "User Activities" menu item 📊
- Kept dashboard URL unchanged to preserve login flow 🔒
- Also adjusted welcome banner max-width for better layout 📐
"But I don't want to go among mad dashboards," Alice remarked. 🎩
"Oh, you can't help that," said the Cat: "we're all Home here." 🐱
=> Rename Dashboard to Home and swap icons 🔄

server/src/components/tickets/ticket/TicketDetails.tsx
This PR adds a popout button to the ticket drawer that allows users to open the ticket in a new window to see all the details. The button is only displayed when viewing a ticket in a drawer.
- Added an "Open in new window" button to the ticket drawer header
- Button uses the ExternalLink icon from Lucide React
- Button only appears when the ticket is viewed in a drawer
- Clicking the button opens the ticket in a new browser tab/window
To test this feature:
1. Open a ticket from a list view (which opens in a drawer)
2. Verify the "Open in new window" button appears in the top-right corner of the drawer
3. Click the button and verify the ticket opens in a new browser tab/window with the full ticket details page
@arynshimmy can click here to [continue refining the …
=> Add popout button to ticket drawer for opening tickets in a new window

server/src/app/auth/signin/page.tsx, server/src/components/auth/ClientLoginForm.tsx
This PR removes the register button from the client portal sign-in page to prevent new user registration through the client portal interface.
- **Removed Register Button**: Completely removed the "Register" button from the `ClientLoginForm` component
- **Updated Interface**: Removed the `onRegister` prop from the `ClientLoginForm` component interface
- **Simplified Layout**: Changed the layout from `flex justify-between` to a simple container for the "Forgot password" link
- **Removed UI Reflection**: Removed the register button from the UI reflection system registration
- **Updated Parent Component**: Removed the `onRegister` prop from the parent signin page component
- `server/src/components/auth/ClientLoginForm.tsx` - Removed register button and related functionality
- …
=> Remove register button from client portal sign-in page

Dockerfile.build
- Replace manual Sharp uninstall/reinstall with `--include=optional` flag
- Automatically detect correct platform binaries for Alpine musl
- Should resolve the "linuxmusl-x64 runtime" error during Docker builds
=> Fix Sharp installation for Alpine Linux builds

server/migrations/20250719190720_add_pubsub_initialised_at_to_google_config.cjs
- Add database migration for `pubsub_initialised_at` field to `google_email_provider_config` table
- Required for Gmail Pub/Sub single initialization refactor idempotency protection
- Field tracks when Pub/Sub was last initialized to prevent duplicate setups within 24 hours
- **Migration**: `20250719190720_add_pubsub_initialised_at_to_google_config.cjs`
- Adds nullable `TIMESTAMPTZ` column to `google_email_provider_config`
- Provides rollback capability via down migration
- CitusDB compatible (simple column addition)
This migration supports the Gmail Pub/Sub single initialization refactor that eliminates duplicate `setupPubSub()` calls (4x → 1x) by adding idempotency protection with 24-hour cooldown tracking.
=> feat: add database migration for pubsub_initialised_at field

server/scripts/bypass-tenant-onboarding.ts
- Add CLI script to bypass tenant onboarding by setting `onboarding_skipped` flag to true
- Script can update all tenants or target specific tenant by ID
- Includes dry run mode for safe testing before applying changes
- Reads database connection details from environment variables and secrets
- **Safe operation**: Dry run mode to preview changes before applying
- **Flexible targeting**: Update all tenants or specify a single tenant ID
- **Comprehensive reporting**: Shows current state, planned changes, and verification
- **Database integration**: Uses existing connection patterns from other scripts
- **CLI interface**: Built-in help and clear command-line options
```bash
./server/scripts/bypass-tenant-onboarding.ts --dry-run
./server/scripts/bypass-tenant-onboarding.ts …
```
=> feat: add tenant onboarding bypass script

shared/utils/encryption.ts
Updated encryption utilities to use `nextauth_secret` instead of `alga_auth_key` for password hashing and verification.
- Modified `hashPassword()` to retrieve 'nextauth_secret' instead of 'alga_auth_key'
- Modified `verifyPassword()` to retrieve 'nextauth_secret' instead of 'alga_auth_key'
This change maintains consistency with the authentication system configuration and standardizes the secret naming convention.
=> refactor: Replace alga_auth_key with nextauth_secret in encryption utilities

helm/templates/secret.yaml
- Modified `helm/templates/secret.yaml` to support user-defined secret values
- Allows configuration of `NEXTAUTH_SECRET`, `CRYPTR_KEY`, and `TOKEN_SECRET_KEY` via values.yaml
- Falls back to generating random values if secrets are not specified
This PR modifies the Helm secret template to check for secret values in `.Values.secrets` before generating random values. This enhancement allows users to:
1. Specify their own secret values in their values.yaml file
2. Maintain consistent secrets across deployments
3. Use existing secrets when migrating or upgrading
The template logic:
- First checks if `.Values.secrets` exists
- For each secret, uses the provided value if available
- Falls back to generating random 32-character alphanumeric values if not specified
- Base64 encodes all values as …
=> feat: Add support for configurable secrets in Helm values

helm/templates/deployment-dev.yaml
The dev (sebastian-dev) Deployment was mounting the documents PersistentVolumeClaim, which is not multi-attach capable. This change removes the storage-volume PVC and mount from deployment-dev.yaml so the PVC is only bound to the main sebastian Deployment.
=> fix: remove documents PVC from dev deployment

server/entrypoint.sh, server/src/app/api/auth/[...nextauth]/options.ts, services/workflow-worker/entrypoint.sh
- Remove verbose logging from `get_secret` function in entrypoint scripts
- Update logger import path in NextAuth options
1. **server/entrypoint.sh** and **services/workflow-worker/entrypoint.sh**:
- Removed log messages when using environment variables instead of Docker secrets
- Removed log messages when neither secret file nor environment variable is found
- These messages were creating unnecessary noise in logs
2. **server/src/app/api/auth/[...nextauth]/options.ts**:
- Updated logger import from `@alga-psa/shared/dist/core/logger.js` to `@alga-psa/shared/core/logger.js`
- This uses the direct import path instead of the built distribution path
=> fix: remove verbose logging from secret retrieval and update import path

ee/temporal-workflows/src/config/startupValidation.ts, helm/templates/deployment-dev.yaml, helm/templates/deployment.yaml, server/src/middleware/authorizationMiddleware.ts, shared/utils/encryption.ts
This PR addresses several issues with vault agent secret injection:
- Remove unnecessary command override for vault agent in deployment template
- Trim whitespace in vault agent secret injection template and remove redundant args
- Update vault agent secret injection keys and remove unnecessary logging
- Remove template-style vault agent secret injection for alga_auth_key
- Include nextauth secret in temporal worker startup validation
- Remove fallback logic for missing enc keys
- Remove redundant fallback
These changes improve the reliability and security of secret injection in the vault agent setup.
=> Fix vault agent secret injection and related improvements

pgbouncer/Dockerfile, pgbouncer/entrypoint.sh, pgbouncer/pgbouncer.ini.template, pgbouncer/userlist.txt.template
- Replace sed-based password substitution with envsubst to handle special characters
- Fixes issues with passwords containing `@`, `$`, `#`, and other special characters
- Adds only 2MB to the Docker image
- Add `gettext` package for the `envsubst` utility
- Convert configuration files to templates:
- `pgbouncer.ini` → `pgbouncer.ini.template`
- Create `userlist.txt.template`
- Update `entrypoint.sh` to use `envsubst` for safe variable substitution
- Clear sensitive environment variables after substitution for improved security
- **Perfect character handling**: No escaping needed for any special characters
- **Improved security**: Passwords cleared from environment after use
- **Cleaner code**: Removed complex sed escaping logic
- **Minimal overhead**: Only 2MB added to image size
=> Fix pgbouncer password escaping using envsubst

ee/temporal-workflows/src/activities/email-activities.ts
This PR adds a Client Portal login link to the welcome email (both HTML and plain text variants).
Changes
- HTML template: Adds a dedicated “Client Portal Login” link in the credentials section and a second primary button (“Open Client Portal”).
- Plain text template: Adds a “Client Portal Login” line and includes the client-portal URL in the getting started steps.
- URL format: `${APPLICATION_URL}/auth/signin?callbackUrl=/client-portal/dashboard` with trailing slash handling.
Context
- Client portal sign-in is handled by the shared sign-in page using the `callbackUrl` query param to route users to `/client-portal/dashboard` after authentication.
Testing
- Verify `APPLICATION_URL` is set in the worker environment.
- Send a test welcome email; confirm both links render and navigate …
=> Add Client Portal login link to welcome email

ee/docs/plans/s3-deployment-plan.md, ee/server/src/lib/storage/providers/S3StorageProvider.ts, helm/templates/deployment-dev.yaml, helm/templates/deployment.yaml, helm/templates/s3-storage-credentials.yaml, helm/templates/storage-pvc.yaml, package-lock.json, server/next.config.mjs, server/src/config/storage.ts, server/src/lib/initializeApp.ts, server/src/lib/storage/StorageProviderFactory.ts, shared/models/ticketModel.ts, shared/workflow/actions/emailWorkflowActions.ts, shared/workflow/init/registerWorkflowActions.ts
This PR implements S3 storage enablement for Enterprise edition and Helm wiring for MinIO secrets.
Highlights:
- Register EE S3 provider at runtime (initializeApp) via global provider
- Factory treats EE when EDITION or NEXT_PUBLIC_EDITION=enterprise
- Allow S3 endpoint + path-style for MinIO in EE provider
- Fix STORAGE_LOCAL_MAX_FILE_SIZE usage in config
- Helm: add optional storage-credentials secret; support existing secret via secretRef
- Deployment sets EDITION envs and reads S3 creds via secretRef
Helm values (hosted):
- S3 enabled with bucket alga-psa-docs
- endpoint http://minio.nineminds.svc.cluster.local:9000
- secretRef uses `minio-credentials` with keys MINIO_ACCESS_KEY/MINIO_SECRET_KEY
=> Enable EE S3 provider + Helm secretRef; fix local env var

shared/models/ticketModel.ts, shared/workflow/actions/emailWorkflowActions.ts, shared/workflow/init/registerWorkflowActions.ts
Removes unused 'metadata' from comment creation paths.
- shared/workflow/init/registerWorkflowActions.ts: drop 'metadata' param from create_comment_from_email
- shared/models/ticketModel.ts: remove metadata from validation schemas/interfaces and DB insert
This simplifies the API and avoids schema mismatches in environments where comments.metadata does not exist.
=> Remove unused comment metadata

docs/AI_coding_standards.md, ee/docs/plans/microsoft-inbound-email-parity.md, ee/server/src/components/GmailProviderForm.tsx, ee/server/src/components/MicrosoftProviderForm.tsx, scripts/ms-graph-list-subscriptions.cjs, scripts/ms-graph-list-subscriptions.js, server/src/app/api/auth/microsoft/callback/route.ts, server/src/app/api/email/oauth/initiate/route.ts, server/src/app/api/email/webhooks/microsoft/route.ts, server/src/components/GmailProviderForm.tsx, server/src/components/MicrosoftProviderForm.tsx, server/src/lib/actions/email-actions/oauthActions.ts, server/src/middleware/express/authMiddleware.ts, server/src/services/email/providers/MicrosoftGraphAdapter.ts, server/src/utils/email/oauthHelpers.ts
Summary:
- Microsoft vs Gmail inbound parity
- DB-backed token load/refresh for Microsoft
- Webhook persistence in email_providers and microsoft_email_provider_config
- Enriched INBOUND_EMAIL_RECEIVED events with full emailData
- Single-tenant Microsoft OAuth
- Tenant-specific authority for authorize, token exchange, and refresh (fixes AADSTS50194)
- UI refactor
- CE/EE Microsoft and Gmail forms call server actions (no x-api-key in UI)
- Exempt /api/email/oauth/initiate from API-key middleware for authenticated UI
- Tooling: adds scripts/ms-graph-list-subscriptions.cjs; improved error logging
- Docs: updates EE plan to mark completed tasks
Testing:
- Microsoft: set MICROSOFT_TENANT_ID to tenant GUID; OAuth popup works; enriched events published
- Gmail: OAuth via server action; no API key …
=> Microsoft inbound email parity, single-tenant OAuth, and UI server-action refactor

helm/templates/deployment.yaml, helm/values.yaml, server/src/lib/actions/email-actions/oauthActions.ts
Switch OAuth RBAC gating from non-existent `emailproviders` to existing `system_settings`.
- Resource: `system_settings`
- Action: `create` when adding, `update` when editing (via `providerId`)
- File: `server/src/lib/actions/email-actions/oauthActions.ts`
This aligns with existing RBAC permissions in prod until a dedicated `emailproviders` resource is added.
=> RBAC: gate email OAuth using system_settings

helm/templates/deployment-dev.yaml, helm/templates/deployment.yaml, server/src/app/api/auth/microsoft/callback/route.ts, server/src/app/api/email/webhooks/microsoft/route.ts, server/src/lib/actions/email-actions/emailProviderActions.ts, server/src/services/email/providers/MicrosoftGraphAdapter.ts, server/src/services/email/providers/base/BaseEmailAdapter.ts
This PR resolves Microsoft Graph subscription validation failures and a schema mismatch during persistence.
Root Causes
- Validation failure: Microsoft Graph calls the `notificationUrl` with a `validationToken`. Our POST handler didn’t echo it and sometimes attempted to parse an empty body, causing 500s; Graph responded with `400 ValidationError` and message "OK" (we replied "OK" instead of the token).
- Persistence mismatch: After subscription creation we attempted to write `email_providers.webhook_id`, which doesn’t exist. The canonical fields are in `microsoft_email_provider_config`.
Fixes
- Webhook POST validation handling
- Echo `validationToken` from headers or query params as plain text with 200.
- Robust body parsing: if empty or non-JSON during validation probes, respond 200 to …
=> Fix Microsoft Graph webhook validation and persistence

ee/server/src/components/GmailProviderForm.tsx, server/src/components/EmailProviderConfiguration.tsx, server/src/components/EmailProviderList.tsx, server/src/components/EmailProviderSelector.tsx, server/src/components/GmailProviderForm.tsx, server/src/components/MicrosoftProviderForm.tsx, server/src/components/ProviderSetupWizardDialog.tsx, server/src/components/admin/InboundTicketDefaultsManager.tsx, server/src/components/forms/InboundTicketDefaultsForm.tsx, server/src/components/providers/gmail/useOAuthPopup.ts, server/src/components/ui/Dialog.tsx
This PR improves the Email Provider configuration UX and reliability.
Highlights
- Edit in Drawer: Use the app Drawer for editing providers; keep Add in dialog wizard.
- Add wizard: New ProviderSetupWizardDialog integrates selector + form.
- OAuth popup: Fix stale state when popup is closed early; resets to idle and shows message.
- Defaults wording: Rename Channel → Board in defaults list and form.
- Form UX: Surface validation/errors at the top of Gmail/Microsoft forms.
- Dialog polish: Constrain dialog height and make content scrollable.
Test plan
- Add a provider via the wizard dialog; verify header hides on selector.
- Edit an existing provider; confirm form opens in Drawer and closes on success/cancel.
- Start Gmail auth and close the popup early; button re-enables and message is …
=> Email providers: edit in Drawer; add wizard dialog; OAuth popup close; Boards label

shared/package.json
Fix ESM subpath exports for shared extensions
- Add exports for `./extensions/domain.js`, `./extensions/installs.js`, and `./extensions/types.js` in `shared/package.json`.
- Resolves `ERR_PACKAGE_PATH_NOT_EXPORTED` when the Temporal worker imports `@alga-psa/shared/extensions/domain.js`.
Validation
- Build shared and temporal worker Docker image to ensure import resolution.
- Helm deploy should now start without the ESM error.
Follow-ups
- Consider a CI check that fails on unexported subpath imports from `@alga-psa/shared`.
=> shared: export extensions subpaths for ESM resolution

server/src/lib/actions/tenant-settings-actions/tenantSettingsActions.ts, server/src/lib/actions/ticket-actions/ticketDisplaySettings.ts, server/src/lib/models/userPreferences.tsx
Updated tenant settings actions, ticket display settings, and user preferences models to use literal Date objects instead of knex.fn.now() for timestamp fields. This ensures compatibility with Citus distributed PostgreSQL while maintaining the same functionality. All timestamp updates now use explicit Date instances rather than database functions.
And down the rabbit hole we go, where database functions become literal tea-time dates! 🐇⏰☕️
=> Replace knex.fn.now() with literal timestamps for Citus compatibility

ee/server/src/app/api/ext-bundles/upload-proxy/route.ts, ee/server/src/components/settings/extensions/InstallerPanel.tsx, ee/server/src/lib/actions/extBundleActions.ts, ee/server/src/lib/storage/bundles/s3-bundle-store.ts, ee/server/src/lib/storage/bundles/types.ts
- Add contentLength to PutObjectOptions (bundle store types)
- Propagate contentLength through S3 bundle store to client
- Supply contentLength from ext upload server action
- Supply contentLength from API upload-proxy route
Prevents S3/compat providers from receiving undefined decoded-content-length
in streamed uploads, fixing failures like:
"Invalid value \"undefined\" for header \"x-amz-decoded-content-length\"".
=> S3 uploads: pass explicit contentLength to avoid invalid x-amz-decoded-content-length

ee/docs/extension-system/runner.md, ee/runner/src/http/server.rs, ee/runner/src/registry/client.rs, shared/package.json
Runner: authenticate registry calls with ALGA_AUTH_KEY
- Attach `x-api-key` header from env `ALGA_AUTH_KEY` for:
- Root host lookup: `GET /api/installs/lookup-by-host?host=...`
- Strict validation client: `GET /api/installs/validate?tenant=...&extension=...&hash=...`
- Update Runner docs to include `REGISTRY_BASE_URL` and `ALGA_AUTH_KEY` in configuration.
Why:
- EE server enforces API key auth on `/api/*`. Runner’s registry calls were receiving 401.
Infra follow-up (Knative KService):
- Ensure the Runner deployment sets `ALGA_AUTH_KEY` (via Vault/Secret).
Example (Knative Service spec):
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
name: runner
namespace: <ns>
spec:
template:
spec:
containers:
- image: <runner-image>
env:
- name: REGISTRY_BASE_URL
value: …
```
=> runner: send ALGA_AUTH_KEY as x-api-key to registry

scripts/ms-graph-list-subscriptions.cjs, server/src/app/api/auth/microsoft/callback/route.ts, server/src/services/email/providers/MicrosoftGraphAdapter.ts, server/src/utils/email/oauthHelpers.ts
Summary
- Add --user flag to scripts/ms-graph-list-subscriptions.cjs to display actual user-scoped resources by replacing /me with /users/<user> in the summary output while preserving raw JSON output.
- Standardize Microsoft OAuth endpoints to use /common authority in callback, token refresh, and auth URL generation to ensure multi-tenant delegated flows.
Details
- Script: lists subscriptions and, when --user is provided, shows normalized resource paths (e.g., /users/alice@contoso.com/...). Also prints original resource for clarity.
- OAuth: Switched authorize and token endpoints to https://login.microsoftonline.com/common/... in:
- server/src/app/api/auth/microsoft/callback/route.ts
- server/src/services/email/providers/MicrosoftGraphAdapter.ts
- server/src/utils/email/oauthHelpers.ts …
=> Microsoft Graph: normalize /me with --user; use /common authority for OAuth

server/src/components/client-portal/tickets/TicketDetails.tsx, server/src/components/editor/RichTextViewer.tsx, server/src/components/tickets/ticket/CommentItem.tsx, server/src/components/tickets/ticket/TicketConversation.tsx, server/src/components/tickets/ticket/TicketDetails.tsx
- Add optimistic update in client portal `TicketDetails.handleSave` and merge after refetch to prevent stale overwrite updated_at` for the edited comment
- Force conversation list remount via `conversationVersion` key to avoid stale subtrees post-save
- Make `RichTextViewer` remount on content changes using a keyed inner component (`ViewerCore`) and computed `contentKey`
- Key `CommentItem` and `RichTextViewer` by `comment_id` + `updated_at` (and note length in list) to ensure re-init with fresh content
- Sync `editedContent` in `CommentItem` when re-entering edit mode for an updated comment
- Add diagnostic logs across save, render, and viewer initialization to trace content/timestamps
- Fix TypeScript issue by casting refetched ticket to `TicketWithDetails` before accessing …
=> feat(client-portal): show edited comment immediately after save

docker-compose.ee.yaml, helm/README.md, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/istio/gateway.yaml, helm/templates/istio/virtualservice.yaml, helm/values.yaml, shared/package.json
Backports Istio ingress support to the 0.9.0 release branch.
What’s included
- New templates under helm/templates/istio/
- Gateway (HTTP :80) with configurable hosts
- VirtualService with routes for green/blue and apex default
- New values under `istio.*` (disabled by default)
- Default hosts updated to dash form (green-sebastian / blue-sebastian)
- README guidance to enable and use with Cloudflare Tunnel (HTTP origin)
Why
- Aligns Istio ingress with current environment using Cloudflare termination and HTTP to origin.
- Supports single-level hostnames compatible with Universal SSL.
Base: release/0.9.0
Cherry-picked from: fb1a3cea (squash of changes since d8082e9d)
=> feat(helm): Istio Gateway/VirtualService for 0.9.0 (dash hostnames)

README.md, docker-compose.prebuilt.ce.yaml, docker-compose.prebuilt.ee.yaml, docs/setup_guide.md
- Add Production Setup (Persistent Storage) section to setup guide\n- Add named volumes for Postgres and file storage in CE/EE prebuilt compose\n- README note pointing to volumes and guide\n\nThis guides users toward a more production-ready configuration with persistent volumes and includes backup/restore examples for DB and files.
=> docs: production persistence volumes + backups

docs/AI_coding_standards.md, docs/migrations/local-ee-migrations.md, docs/overview.md, server/knexfile.cjs, server/package.json, server/scripts/run-ee-migrations.js
This PR documents and enables running EE migrations locally without copying into the repo.
Changes:
- docs/migrations/local-ee-migrations.md: temp-dir overlay approach, commands, troubleshooting
- docs/AI_coding_standards.md: add "Local EE migrations" section linking to the new doc
- docs/overview.md: pointer in Database section
- server/knexfile.cjs: allow overriding migrations dir via MIGRATIONS_DIR and loadExtensions
- server/scripts/run-ee-migrations.js: helper to merge CE+EE into tmp and run Knex
- server/package.json: add script migrate:ee
Rationale:
- Avoids accidental duplication or commits of merged migrations locally
- Mirrors CI "merge then run" behavior while keeping the workspace clean
Follow-up options:
- Add migrate:ee:down or targeted up/down wrappers
- Optionally …
=> docs: local EE migrations runner + env override

server/src/components/tickets/ticket/TicketDetails.tsx
Prior to this fix, only the first comment would automatically show, but now, all comments will show up on the ticket screen immediately after they are added
Before:
https://github.com/user-attachments/assets/34fabb52-55c4-43bf-be71-49fc030f730f
After:
https://github.com/user-attachments/assets/b95f2fcd-de90-4631-979c-88e35608458d
=> Subsequent ticket comments now show automatically

server/src/components/interactions/QuickAddInteraction.tsx, server/src/components/ui/Dialog.tsx
Edit interaction dialogue had two scrollbars, one of them completely unnecessary, so it was removed.
=> Removed unnecessary 2nd scroll in edit interaction

ee/server/seeds/onboarding/06_project_task_statuses.cjs, server/src/components/tags/TagInput.tsx, server/src/lib/actions/project-actions/projectActions.ts
- Add onboarding seed for default project task statuses (To Do, In Progress, Done)
- Fix TagInput infinite loop by memoizing current tag texts
- Refactor project creation to handle both standard and regular status tables
- Improve backward compatibility for project task status management
Impact: Ensures consistent project task status setup across tenants and prevents UI performance issues in tag input.
Follow the yellow brick road of statuses, for there's no place like a properly seeded database! 🧙‍♂️✨
=> Add project task statuses seed and improve status handling

ee/temporal-workflows/src/activities/__tests__/portal-domain-activities.git.test.ts, ee/temporal-workflows/src/activities/__tests__/portal-domain-activities.test.ts, ee/temporal-workflows/src/activities/portal-domain-activities.ts, ee/temporal-workflows/src/config/startupValidation.ts
- require the portal worker to define `PORTAL_DOMAIN_BASE_VIRTUAL_SERVICE`
- merge each tenant VirtualService host and gateway into the shared base VS during reconciliation
- extend test coverage for TLS routing and base VirtualService updates
=> Ensure portal domains update base VirtualService

ee/server/seeds/onboarding/06_project_task_statuses.cjs
Temporarily disables the `06_project_task_statuses.cjs` onboarding seed to fix tenant creation failures.
The tenant creation workflow is failing with:
```
null value in column "created_by" of relation "statuses" violates not-null constraint
```
This occurs because:
1. The seed tries to insert statuses with `created_by=null`
2. The `statuses` table has a NOT NULL constraint on `created_by` from the initial schema
3. Onboarding seeds run **before** any users exist in the workflow
- **Sept 2024**: `statuses` table created with `created_by uuid NOT NULL`
- **Aug 5, 2025**: Workflow refactored to run seeds before user creation (commit `59f2ad79`)
- **Sept 26, 2025**: New seed `06_project_task_statuses.cjs` added (commit `2ca1ca6a`)
- This is the first seed file that inserts into a table with a …
=> fix: temporarily disable project task statuses seed

Dockerfile, docs/setup_guide.md, ee/server/setup/create_database.js, hocuspocus/entrypoint.sh, hocuspocus/server.js, pgbouncer/entrypoint.sh, pgbouncer/pgbouncer.ini.template, pgbouncer/userlist.txt.template, scripts/run_async.sh, server/migrations/20251004000100_add_board_id_to_inbound_ticket_defaults.cjs, server/seeds/dev/04b_email_processing_workflow_from_source.cjs, server/seeds/dev/80_itil_categories.cjs, server/setup/create_database.js, tmp/test-install/set-image-tag.sh
- default the setup scripts and Hocuspocus entrypoint to use \
- harden the dev ITIL categories seed so it works against both schema variants
- add setup-troubleshooting guidance for recovering from credential drift
- ship \ to simplify long-running compose commands
- docker compose -p alga-psa -f docker-compose.prebuilt.base.yaml -f docker-compose.prebuilt.ce.yaml -f docker-compose.override.yaml --env-file server/.env --env-file .env.image up -d
- docker logs release011test_setup_ce
=> Align Hocuspocus defaults and document recovery steps

docs/setup_guide.md, docs/setup_guide_windows.md
- surface the initial login credential instructions immediately after the compose startup command
- sync the Windows setup guide with the primary guide, keeping Windows-specific notes
- document storage, monitoring, troubleshooting, and upgrade guidance for Windows users to match main docs
- not applicable
=> docs: surface initial login credentials earlier
