server/src/app/msp/contacts/page.tsx
server/src/components/contacts/Contacts.tsx

🪄 Poof No more flashy contact avatars causing a ruckus!

flashy contact avatars

---

server/migrations/20241111185522_add_shared_document_types.cjs
server/migrations/20241111201025_allow_null_type_id_on_documents.cjs
server/seeds/dev/add_shared_document_types.cjs
server/src/app/msp/documents/page.tsx
server/src/interfaces/document.interface.tsx
server/src/lib/actions/document-actions/documentActions.ts

• Adds shared_document_types table
• Makes document type_id nullable
• Seeds common MIME types
• Updates document preview generation
• Adds type detection for uploads

Add shared document types and make document type field nullable

---

docs/AI_coding_standards.md
server/migrations/20241111201500_create_document_associations.cjs
server/migrations/20241111204243_migrate_document_associations.cjs
server/src/app/api/documents/download/[fileId]/route.ts
server/src/app/msp/contacts/[id]/page.tsx
server/src/app/msp/documents/page.tsx
server/src/components/companies/CompanyDetails.tsx
server/src/components/documents/DocumentSelector.tsx
server/src/components/documents/DocumentStorageCard.tsx
server/src/components/documents/DocumentUpload.tsx
server/src/components/documents/Documents.tsx
server/src/components/tickets/TicketConversation.tsx
server/src/interfaces/document-association.interface.ts
server/src/interfaces/document-association.interface.tsx
server/src/interfaces/document.interface.tsx
server/src/lib/actions/document-actions/documentActions.ts
server/src/lib/models/document-association.tsx
server/src/lib/models/document.tsx
server/src/lib/utils/documentUtils.ts
server/src/models/document-association.ts

This commit introduces a new document association system and improves the overall document management functionality. The changes allow documents to be associated with multiple entities (tickets, companies, contacts, schedules) through a new document_associations table, replacing the previous direct relationship columns.
Key Changes:
- Add new document_associations table with tenant isolation and RLS policies
- Create migration to move existing document relationships to new association table
- Implement document association/disassociation functionality
- Add document download endpoint and route
- Enhance document preview and file type handling
- Improve document filtering and search capabilities
UI Improvements:
- Add ability to link existing documents to entities
- Implement document grid …

feat: implement document associations and enhance document management

---

docs/asset_management.md
server/migrations/20241112031330_create_asset_management_tables.cjs
server/migrations/20241112031331_create_asset_associations.cjs
server/src/app/msp/assets/page.tsx
server/src/components/assets/AssetDashboard.tsx
server/src/components/assets/AssociatedAssets.tsx
server/src/components/assets/CreateAssetDialog.tsx
server/src/components/assets/CreateTicketFromAssetButton.tsx
server/src/components/tickets/TicketDetails.tsx
server/src/config/menuConfig.ts
server/src/interfaces/asset.interfaces.tsx
server/src/interfaces/index.ts
server/src/lib/actions/asset-actions/assetActions.ts
server/src/lib/actions/ticket-actions/ticketActions.ts
server/src/lib/schemas/asset.schema.ts
server/src/lib/schemas/ticket.schema.ts
server/src/models/asset.ts

feat(asset-management): implement comprehensive asset management system
This major feature addition introduces a complete asset management system for our MSP PSA platform, enabling robust IT asset tracking and management across multiple clients.
Key Components:
- Database schema for assets, asset types, and asset associations
- Core asset management models and interfaces
- Server actions for CRUD operations
- Asset-ticket integration with bi-directional linking
- Row-level security and tenant isolation
- Asset history tracking and audit logging
Technical Details:
- Hierarchical asset type system with inheritance
- Flexible attribute schemas via JSONB
- Complete change history tracking
- Asset association system for linking to tickets/projects
- Migration files for database setup
This lays …

Initial asset management feature

---

server/migrations/20241112031330_create_asset_management_tables.cjs
server/migrations/20241112031332_create_asset_document_associations.cjs
server/migrations/20241112031333_create_asset_ticket_associations.cjs
server/migrations/20241112031334_create_maintenance_scheduling.cjs
server/seeds/dev/62_asset_types.cjs
server/seeds/dev/63_assets.cjs
server/seeds/dev/64_asset_maintenance.cjs
server/seeds/dev/65_asset_documents.cjs
server/seeds/dev/66_asset_tickets.cjs
server/src/app/msp/assets/page.tsx
server/src/components/assets/AssetDashboard.tsx
server/src/components/companies/CompanyAssets.tsx
server/src/components/companies/CompanyDetails.tsx
server/src/config/menuConfig.ts
server/src/interfaces/asset.interfaces.tsx
server/src/lib/actions/asset-actions/assetActions.ts
server/src/lib/schemas/asset.schema.ts
server/src/models/asset.ts

This major update introduces a robust asset management and maintenance tracking system with several key features:
1. Asset Management Enhancements:
- Improved data modeling with proper company associations
- Enhanced asset listing with detailed company information
- Better date handling and ISO string standardization
2. Maintenance Scheduling:
- Preventive maintenance scheduling
- Maintenance history tracking
- Compliance monitoring and reporting
- Configurable maintenance types and frequencies
3. Documentation & Associations:
- Document management for assets
- Ticket associations for maintenance requests
- Service history tracking
- Asset-company relationships
4. Dashboard & Reporting:
- Asset status distribution visualization
- Maintenance compliance metrics
- Company-specific asset …

feat(assets): comprehensive asset management and maintenance system

---

server/src/components/tickets/TicketingDashboard.tsx
server/src/lib/schemas/ticket.schema.ts

Toto, I've a feeling we're not sending empty channels anymore. Switched to NULL because empty is as useless as the Wizard's promises! 🌪️ 🏠

🧙‍♂️ Follow the Yellow Brick Road... to NULL!

---

server/src/components/projects/ProjectDetail.tsx
server/src/components/projects/TaskEdit.tsx
server/src/components/projects/TaskQuickAdd.tsx
server/src/lib/actions/projectActions.ts
server/src/lib/models/project.ts

Behold! Our application has evolved with grace and power:
- Phases can now gracefully exit stage left with proper deletion 🎬
- Lucide icons take the spotlight, bringing visual harmony 🎨
- Tasks now behave with proper etiquette when cancelled 🎭
- Build errors banished from our theater of operations 🛠️
"Pay no attention to the bugs behind the curtain!"

✨ Phase Management & Task Controls: The Grand Update 🎭

---

server/src/app/msp/assets/new/page.tsx
server/src/components/companies/CompanyAssets.tsx
server/src/utils/logger.tsx

This commit introduces a new asset creation page with comprehensive form handling for different types of IT assets. The implementation includes:
- New React component for asset creation with type-specific form fields
- Support for multiple asset types: workstations, servers, network devices, mobile devices, and printers
- Dynamic form validation and data submission
- Integration with asset creation API
- Improved asset type filtering in CompanyAssets component
Key changes:
- Added new page.tsx under /msp/assets/new
- Implemented extensive form handling with type-specific fields
- Updated asset listing filter to handle 'all' types correctly
- Modified asset creation link path in CompanyAssets
- Added proper form validation and error handling
Technical details:
- Uses React hooks for state …

feat: Add new asset creation page with dynamic form fields

---

server/src/components/billing-dashboard/BillingCycles.tsx

• Removes refresh button and icon
• Simplifies header layout
• Reduces unused imports

Remove refresh button from billing cycles display

---

server/src/components/projects/ProjectDetail.tsx
server/src/components/projects/TaskEdit.tsx
server/src/components/projects/TaskQuickAdd.tsx
server/src/lib/actions/projectActions.ts
server/src/lib/models/project.ts

added checklist counters, fixed donut chart counter (wbs codes, again)

Project tasks update

---

server/src/components/technician-dispatch/ScheduleEvent.tsx
server/src/components/technician-dispatch/TechnicianDispatchDashboard.tsx
server/src/components/technician-dispatch/TechnicianRow.tsx
server/src/components/technician-dispatch/TechnicianScheduleGrid.tsx
server/src/components/technician-dispatch/TimeHeader.tsx
server/src/components/technician-dispatch/TimeSlot.tsx
server/src/interfaces/drag.interfaces.ts
server/src/interfaces/event.interfaces.ts
server/src/interfaces/schedule.interfaces.ts

- Add unified hover state styles for buttons and links
- Implement smooth transition animations (0.2s ease-in-out)
- Ensure hover states meet WCAG contrast requirements
- Add subtle scale transform for enhanced feedback
- Fix hover persistence bug on touch devices
"My dear, true hover states are like flying monkeys - they must be handled with care
and precision, or they'll carry you away to places unknown!"
- Glinda the Good Witch, probably

feat: improve hover experience on interactive elements

---

server/src/components/time-management/AddWorkItemDialog.tsx
server/src/components/time-management/WorkItemPicker.tsx

• Add fixed height and scrollable container
• Move search box to sticky header
• Improve overflow handling
• Clean up flexbox layout structure

Fix scrolling behavior in work item picker dialog

---

server/src/app/globals.css
server/src/components/time-management/TimePeriodList.tsx

style: improve table layout and width consistency
Updates table styling to ensure consistent full-width layout and better column spacing. Adds fixed column widths and adjusts CSS rules for Radix UI Table components to prevent layout shifts.

Time sheet list should extend across the viewport

---

server/src/components/projects/TaskCard.tsx
server/src/components/projects/TaskForm.tsx
server/src/interfaces/project.interfaces.ts
server/src/lib/actions/ticket-actions/ticketActions.ts
server/src/lib/models/project.ts

Now you can see at a glance how many munchkin-sized tickets are linked to each task, making project management as clear as the Emerald City's sparkle. 🏰

associated tickets counter for task card

---

server/src/components/layout/Header.tsx
server/src/components/projects/TaskForm.tsx

abolish dashboard

---

server/src/app/client-portal/dashboard/page.tsx
server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/BillingPlans.tsx
server/src/components/billing-dashboard/GenerateInvoices.tsx
server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/BillingPlans.tsx
server/src/components/companies/PlanPickerDialog.tsx
server/src/components/dashboard/DashboardActions.tsx
server/src/components/ui/Dialog.tsx
server/src/interfaces/billing.interfaces.ts
server/src/interfaces/dataTable.interfaces.ts
server/src/lib/actions/billingCycleActions.ts
server/src/lib/actions/initializeApp.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/billing/billingEngine.ts
server/src/lib/billing/createBillingCycles.ts
server/src/lib/jobs/jobScheduler.ts
server/src/test/infrastructure/companyBillingCycle.test.ts

This commit introduces comprehensive billing cycle automation features:
- Add new GenerateInvoices component for managing billing periods
- Implement billing cycle creation and management logic
- Add automated job scheduler for recurring billing cycles
- Enhance date handling for billing periods
- Add test coverage for billing cycle creation
- Fix billing period calculation edge cases
- Update dashboard UI components for better usability
"Oh my! Time flies like billing cycles through the air! But unlike my tea parties, 
these cycles know precisely when to start and end. How wonderfully punctual! 🎩"

feat(billing): implement automated billing cycle generation and management

---

server/src/components/billing-dashboard/TimePeriodForm.tsx
server/src/components/billing-dashboard/TimePeriods.tsx
server/src/components/time-management/TimePeriodList.tsx
server/src/components/time-management/TimeSheet.tsx
server/src/lib/actions/timeEntryActions.ts
server/src/lib/actions/timePeriodsActions.ts
server/src/lib/models/timePeriod.ts

- Add ability to edit existing time periods
- Implement deletion of time periods with confirmation dialog
- Add "No End Date" option for time periods
- Fix date handling and formatting across components
- Improve error handling and validation
- Update UI to support edit/delete actions
- Add checks to prevent modification of periods with existing timesheets
"Now I know I have a heart, because it's breaking from all these date formats!" - Tin Man

Time entry improvements

---

server/src/components/projects/TaskForm.tsx
server/src/components/projects/TaskTicketLinks.tsx
server/src/components/projects/TicketSelect.tsx
server/src/components/settings/general/ChannelPicker.tsx
server/src/components/ui/UserPicker.tsx

✨ Added a search bar at the top to help find your way through the mists 🦁 Blessed the left sidebar with courage-giving filters:
Category selector to sort by type of quest
Assigned To filter to find tasks by fellow adventurers Channel dropdown to navigate different magical realms Status filter to track progress on your journey
Priority selector to know which tasks need ruby slippers first Now Dorothy and her companions can find their tasks faster than you can say "there's no place like home!"
🧙‍♂️ Follow the yellow brick road! 🧙‍♂️

🌈 Lo and behold, dear travelers! The path to linking tickets to project tasks has been enchanted with new magical filtering powers in the dialog

---

package-lock.json
package.json
server/seeds/dev/23_service_catalog.cjs
server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/GenerateInvoices.tsx
server/src/components/billing-dashboard/LineItem.tsx
server/src/components/billing-dashboard/ManualInvoices.tsx
server/src/components/billing-dashboard/PrepaymentInvoices.tsx
server/src/components/billing-dashboard/ServiceCatalogManager.tsx
server/src/interfaces/billing.interfaces.ts
server/src/lib/actions/serviceActions.ts
server/src/lib/models/service.ts

- Add support for manual, automatic, and prepayment invoice types
- Implement error boundaries and validation for robust error handling
- Refactor service catalog to use strong typing and data validation
- Update service types from 'Hourly'/'Monthly' to 'Time'/'Fixed'
- Add React Error Boundary components for better UX
"My dear, when life gives you different types of invoices, just remember - it's not about which road you take, it's about keeping your financial books as sparkling as my crown! ✨👗💫"

feat(billing): Enhance invoice generation with multi-type support

---

docs/AI_coding_standards.md
server/src/lib/services/taxService.ts
server/src/test/infrastructure/manualInvoice.test.ts

- Add tax exempt check in TaxService.calculateTax()
- Add test coverage for tax exempt companies
- Return zero tax amount and rate for tax exempt companies
- Add integration test verifying tax exempt behavior
This change ensures companies marked as tax exempt are not charged
sales tax on their invoices, with proper test coverage to verify
the behavior.
"Under the sea, taxes swim free! 🌊
But Alga the octopus, wise as can be 🐙
Says some friends are exempt, don't you see? ✨
Their invoices float, tax-free with glee! 💫"
- Sebastian the Crab, Chief Financial Crustacean 🦀
& Alga, Senior Tax Tentacle Specialist 🐙

feat(billing): Add tax exempt handling for manual invoices 

---

package-lock.json
server/src/components/projects/TaskForm.tsx
server/src/components/ui/TextArea.tsx

Like Dorothy's journey far beyond a simple yellow brick road, our checklist items can now stretch and wind through multiple lines using the mystical textarea component. No longer confined to single-line constraints, content can flow as freely as Glinda's magical bubbles.
🎯 Changes:
- Replaced input fields with expandable textareas
- Added auto-growing capability for dynamic height
- Preserved checkbox functionality while expanding display

Textarea component for checklist items

---

server/src/components/settings/general/TeamDetails.tsx
server/src/components/settings/general/TeamList.tsx
server/src/components/settings/general/TeamManagement.tsx
server/src/lib/actions/team-actions/teamActions.ts
server/src/lib/models/team.tsx

- Improve team creation flow with required manager selection
- Add confirmation dialog for team deletion
- Change "Save" button to "Rename" for better clarity
- Implement proper cleanup of team members on deletion
- Add cancel option to team creation form
- Fix UI state management after team operations
The changes include:
- Making manager selection mandatory during team creation
- Adding user selection via CustomSelect component
- Implementing proper cascading delete for team members
- Improving error handling and validation
- Enhancing UI/UX with confirmation dialogs and better button labels

feat(teams): enhance team management functionality

---

server/src/components/time-management/ManagerApprovalDashboard.tsx
server/src/components/time-management/TimeSheet.tsx
server/src/components/time-management/TimeSheetApproval.tsx
server/src/lib/actions/timeSheetActions.ts

This commit introduces significant improvements to the timesheet commenting system:
- Optimize comment loading by using Promise.all for parallel fetching
- Improve comment UI with distinct styling for approver vs employee comments
- Add visual indicators for comments requiring changes
- Enhance comment display with better formatting and status indicators
- Update comment refresh logic to show real-time updates
- Fix date formatting issues in timesheet comments
- Refactor timesheet comment fetching for better performance
- Add specialized UI for "Changes Requested" status
- Improve error handling and data validation
The changes provide a more intuitive and responsive commenting experience while maintaining data consistency and improving the overall user interface.

feat: Enhance timesheet comments functionality and UI

---

server/src/components/time-management/TimeEntryDialog.tsx

Key changes:
- Added a `Plus` icon from `lucide-react` for the "Add Entry" button.
- Introduced an `isNew` flag to the `ITimeEntryWithNew` interface to identify newly created entries.
- Added a `tempId` field to `ITimeEntryWithNew` for temporary identification of new entries before they are saved to the database.
- Modified the `handleNewEntries` function to generate and assign a `tempId` using `crypto.randomUUID()` to new entries.
- Updated the "Save" button to be visible only when editing a time entry and moved it to the bottom of the edit form.
- Removed the ability to collapse a new unsaved entry
- Updated the "Add Entry" button to include a `Plus` icon and changed the variant to "outline".
- Disabled the "Add Entry" button while editing a new, unsaved entry to prevent adding multiple …

feat: time entry ui improvements

---

server/seeds/dev/02_users.cjs

remove unused 'role' field

---

.env.example
docker-compose.prod.yaml
docs/overview.md
server/entrypoint.sh
server/setup/create_database.js
server/src/config/envConfig.ts
server/src/empty/components/settings/policy/PolicyManagement.tsx
server/src/empty/lib/auth/index.ts
server/src/lib/auth/ee.ts
server/src/lib/db/db.tsx
server/src/lib/models/user.tsx
server/src/scripts/validateEnvStartup.js
setup/entrypoint.sh

- Add production-specific Docker Compose configuration
- Implement Enterprise/Community Edition module aliasing system
- Add empty implementations pattern for CE features
- Enhance database setup and security:
- Make secrets handling more flexible using Docker secrets
- Add environment variable validation
- Improve seed data handling to prevent duplicate runs
- Update documentation with EE/CE implementation details
- Add PolicyManagement component for CE with upgrade messaging
BREAKING CHANGES:
- Environment variables ALGA_AUTH_KEY, SECRET_KEY, and NEXTAUTH_SECRET are now 
optional when using Docker secrets

refactor(infrastructure): enhance production setup and EE/CE architecture

---

server/src/components/billing-dashboard/QuickAddBillingPlan.tsx
server/src/components/billing-dashboard/ServiceCatalogManager.tsx
server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/PlanPickerDialog.tsx
server/src/components/companies/ServiceCatalog.tsx
server/src/lib/actions/companyBillingPlanActions.ts
server/src/lib/models/service.ts

Key updates:
- Add plan type selection in QuickAddBillingPlan with options for Fixed/Hourly/Usage/Bucket
- Implement confirmation dialogs for service and billing plan deletion
- Add end date handling for billing plans with ongoing/fixed duration options
- Improve error handling in billing plan actions
- Remove duplicate ServiceCatalog component from BillingConfiguration
Technical changes:
- Update service validation schema by separating creation schema
- Add proper typings for error handling
- Fix parameter handling in onSelect callback for PlanPickerDialog
- Add ConfirmationDialog component usage across delete operations
- Enhance datetime input handling for billing plan dates
- Fix error message propagation in companyBillingPlanActions
UI/UX improvements:
- Add proper validation and …

feat(billing): Enhance billing UI and service management

---

docs/AI_coding_standards.md
docs/ui_reflection_system.md
package-lock.json
server/next.config.mjs
server/package.json
server/src/app/layout.tsx
server/src/components/contacts/Contacts.tsx
server/src/components/ui/Button.tsx
server/src/components/ui/Dialog.tsx
server/src/components/ui/Input.tsx
server/src/lib/initializeApp.ts
server/src/types/ui-reflection/ClientUIStateProvider.tsx
server/src/types/ui-reflection/UIStateContext.tsx
server/src/types/ui-reflection/types.ts
server/src/types/ui-reflection/useRegisterUIComponent.ts
tools/ai-automation/README.md
tools/ai-automation/src/index.ts
tools/ai-automation/src/tools/Tool.ts
tools/ai-automation/src/tools/executeScript.ts
tools/ai-automation/src/tools/getUIState.ts
tools/ai-automation/src/tools/index.ts
tools/ai-automation/src/tools/navigateTo.ts
tools/ai-automation/src/tools/takeScreenshot.ts
tools/ai-automation/src/tools/toolManager.ts
tools/ai-automation/src/types/ui-reflection.ts
tools/ai-automation/src/uiStateManager.ts
tools/ai-automation/web/package-lock.json
tools/ai-automation/web/package.json
tools/ai-automation/web/src/lib/ui-reflection/useUIReflection.ts

This comprehensive update introduces a new UI Reflection System that provides 
a live, high-level JSON description of the application's UI state. The system 
enables automated testing, LLM-driven interactions, and real-time UI state 
monitoring.
Key additions:
- WebSocket-based UI state broadcasting
- Component registration system with TypeScript support
- Real-time screenshot streaming capabilities
- Enhanced test harness integration
- UI component metadata tracking
- Stable component ID guidelines
Breaking changes:
- New required 'id' props for components using reflection
- Updated WebSocket port configuration
🐰 "Curiouser and curiouser!" cried Alice, as she watched the UI components 
reflect themselves like mirrors in a digital wonderland. 🪞✨

feat(UI): Add UI Reflection System for automated testing and LLM interactions

---

server/src/types/ui-reflection/UIStateContext.tsx
tools/ai-automation/Dockerfile
tools/ai-automation/src/index.ts
tools/ai-automation/src/tools/executePuppeteerScript.ts
tools/ai-automation/src/tools/index.ts
tools/ai-automation/web/next.config.mjs
tools/ai-automation/web/package-lock.json
tools/ai-automation/web/package.json
tools/ai-automation/web/src/app/api/ai/route.ts
tools/ai-automation/web/src/app/page.tsx
tools/ai-automation/web/src/tools/invokeTool.ts
tools/ai-automation/web/src/tools/prompts.ts
tools/ai-automation/web/src/tools/toolDefinitions.ts

This commit introduces several significant improvements to the AI automation tools:
Core Functionality:
- Add periodic UI state updates with WebSocket support
- Implement new get_ui_state tool for efficient page analysis
- Add execute_puppeteer_script tool for direct browser interaction
- Configure increased HTTP header size for larger payloads
UI Enhancements:
- Add URL input with direct navigation capability
- Add username/password fields for credentials
- Improve chat interface with better message handling
- Add cancel and clear conversation buttons
- Enhance log display with structured entries and timestamps
Code Quality:
- Improve error handling and type safety
- Standardize JSON serialization across endpoints
- Update system prompts with more detailed guidance
- Refactor tool …

feat: enhance AI automation tools and UI improvements

---

tools/ai-automation/src/index.ts
tools/ai-automation/src/tools/executePuppeteerScript.ts
tools/ai-automation/web/package-lock.json
tools/ai-automation/web/package.json
tools/ai-automation/web/src/app/api/ai/route.ts
tools/ai-automation/web/src/app/page.tsx
tools/ai-automation/web/src/lib/llm/anthropic-client.ts
tools/ai-automation/web/src/lib/llm/base-openai-client.ts
tools/ai-automation/web/src/lib/llm/custom-openai-client.ts
tools/ai-automation/web/src/lib/llm/factory.ts
tools/ai-automation/web/src/lib/llm/openai-client.ts
tools/ai-automation/web/src/lib/llm/types.ts
tools/ai-automation/web/src/tools/prompts.ts
tools/ai-automation/web/src/types/messages.ts

Adds new LLM client architecture supporting Anthropic, OpenAI, and custom OpenAI providers:
- Create modular client architecture with base OpenAI implementation
- Add provider-specific implementations for Anthropic and OpenAI
- Implement proper response streaming and tool execution handling
- Add proper error handling and logging for tool execution
- Add timeout safety with promise settling checks
- Update UI to show context dialog for conversation history
The changes improve reliability and maintainability while adding flexibility to switch between different LLM providers.

feat: implement multi-provider LLM support with improved error handling

---

docs/ui_reflection_system.md
server/src/app/auth/signin/page.tsx
server/src/components/auth/ClientLoginForm.tsx
server/src/components/auth/MspLoginForm.tsx
server/src/components/contacts/QuickAddContact.tsx
server/src/components/ui/Checkbox.tsx
server/src/components/ui/ConfirmationDialog.tsx
server/src/components/ui/ContactPickerDialog.tsx
server/src/components/ui/CustomSelect.tsx
server/src/components/ui/Dialog.tsx
server/src/components/ui/GenericDialog.tsx
server/src/components/ui/Input.tsx
server/src/components/ui/Switch.tsx
server/src/components/ui/TextArea.tsx
server/src/types/ui-reflection/UIStateContext.tsx
server/src/types/ui-reflection/types.ts
server/src/types/ui-reflection/useRegisterUIComponent.ts
tools/ai-automation/Dockerfile
tools/ai-automation/src/index.ts
tools/ai-automation/src/puppeteerScripts.ts
tools/ai-automation/web/src/app/api/ai/route.ts
tools/ai-automation/web/src/app/page.tsx
tools/ai-automation/web/src/lib/llm/base-openai-client.ts
tools/ai-automation/web/src/lib/llm/custom-openai-client.ts
tools/ai-automation/web/src/lib/llm/factory.ts
tools/ai-automation/web/src/lib/llm/openai-client.ts
tools/ai-automation/web/src/lib/llm/types.ts
tools/ai-automation/web/src/tools/prompts.ts
tools/ai-automation/web/src/tools/toolDefinitions.ts
tools/ai-automation/web/src/types/messages.ts

- Add parent-child relationships between UI components
- Update UIStateContext to handle component hierarchy
- Refactor component registration to support nested structures
- Add new hooks for child component registration
- Update all UI components to use hierarchical system
- Add typing support for hierarchical relationships
- Improve documentation with hierarchy examples

feat: Implement hierarchical UI reflection system

---

server/src/components/projects/TaskForm.tsx

We should consider making change tracking a more fundamental ui service.

fix: do not show unsaved dialog without changes

---

docs/billing.md
docs/billing_cycles.md
server/migrations/20250105022937_add_is_active_to_company_billing_cycles.cjs
server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/BillingCycles.tsx
server/src/components/billing-dashboard/GenerateInvoices.tsx
server/src/interfaces/invoice.interfaces.ts
server/src/lib/actions/billingCycleActions.ts
server/src/lib/actions/invoiceActions.ts

- Add support for early invoice generation with warnings
- Implement billing cycle reversal functionality
- Extend invoice schema with billing period tracking
- Add new tables for invoice templates, annotations, and time/usage linking
- Improve billing cycle UI with status indicators and actions
- Add comprehensive error handling for invoice generation
- Update interfaces to support new billing cycle states
- Implement hard delete for invoices with proper cleanup
This change improves the billing system's flexibility while maintaining data integrity through proper handling of invoice reversals, credit reissuance, and usage tracking.
🫖 "Curiouser and Curiouser!" cried Alice (The Billing Update)
🐇 "Oh dear! Oh dear! I shall be late!" - Added early invoice generation 🎩 "We're all mad here" - …

feat(billing): Enhance billing cycle management and invoice generation

---

tools/ai-automation/web/src/app/api/ai/route.ts
tools/ai-automation/web/src/app/page.tsx
tools/ai-automation/web/src/lib/llm/base-openai-client.ts
tools/ai-automation/web/src/tools/prompts.ts
tools/ai-automation/web/src/tools/toolDefinitions.ts

- Update type definition for accumulatedInput to handle undefined values
- Add handling for multiple tool calls and improved stream disconnection
- Fix JSON parsing and empty input handling in tool execution
- Update system prompts and standardize prompt references
- Remove welcome message from initial chat state
- Add check for tool index > 0 in base OpenAI client
- Enhance tool definitions with clearer descriptions
- Add guidelines for tool execution flow in system message

refactor: improve LLM streaming and tool execution logic

---

server/src/components/projects/ProjectDetailsEdit.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/lib/models/project.ts

Ensured proper date conversion for editing on project page
Fixed Company picker width on tickets page

Added ordering projects by end date

---

tools/ai-automation/package-lock.json
tools/ai-automation/package.json
tools/ai-automation/src/index.ts
tools/ai-automation/src/puppeteerManager.ts
tools/ai-automation/src/tools/Tool.ts
tools/ai-automation/src/tools/executePuppeteerScript.ts
tools/ai-automation/src/tools/getUIState.ts
tools/ai-automation/src/tools/index.ts
tools/ai-automation/src/tools/toolManager.ts
tools/ai-automation/src/uiStateManager.ts
tools/ai-automation/src/utils/diffUtils.ts
tools/ai-automation/tsconfig.json
tools/ai-automation/web/src/tools/invokeTool.ts
tools/ai-automation/web/src/tools/prompts.ts

Integrates jsondiffpatch to track and report UI state changes after Puppeteer actions. This provides better visibility into how actions affect the application state by:
- Adding computed diffs between old and new UI states after script execution
- Including diffs in both success and error responses
- Removing redundant selector waiting since state changes are now tracked
- Configuring jsondiffpatch for optimized array change detection
Also includes some related improvements:
- Switches to ES modules for better package compatibility
- Increases post-action wait time to 200ms for more reliable state capture
- Improves error handling to return diffs even when scripts fail

feat: Add diff tracking for UI state changes

---

server/src/components/companies/CompanyPicker.tsx
server/src/components/projects/PhaseListItem.tsx
server/src/components/projects/Projects.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/time-management/AddWorkItemDialog.tsx
server/src/components/time-management/WorkItemPicker.tsx
server/src/components/ui/UserPicker.tsx
server/src/lib/actions/workItemActions.ts

feat: Enhance filtering options for work items in TicketingDashboard and WorkItemPicker
- Added advanced filtering options for work items, including:
- Assigned to user (with "Assigned to me" toggle)
- Company filter
- Date range filter (start and end dates)
- Status and priority filters
- Improved UI for filter controls with expandable/collapsible filter sections
- Added a "Reset Filters" button to clear all applied filters
- Updated the WorkItemPicker component to support new filtering capabilities
- Enhanced the search functionality in WorkItemPicker to include additional filters
- Updated the backend to handle new filter parameters in work item queries
- Added error handling and debug logging for filter-related queries
- Added some other minor UI improvements
Pay no attention to the …

Work item filters

---

server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/BillingPlans.tsx
server/src/components/time-management/ManagerApprovalDashboard.tsx
server/src/components/time-management/TimeSheetApproval.tsx
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/timeSheetActions.ts
server/src/lib/billing/billingEngine.ts

- Add ability to view and manage approved timesheets
- Implement timesheet approval reversal functionality
- Add service category change handling for billing plans
- Fix time entry query for billing calculations
- Improve invoice generation error handling
- Update UI to show approved timesheet status with reversal option
- Add safety checks for invoiced entries before reversal
- Enhance billing calculation logging with company names
For when "Oops, I didn't mean to approve that" becomes a feature request 😅

Add timesheet approval management features

---

server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/Invoices.tsx

- Replace action buttons with dropdown menu for cleaner interface
- Add URL-based state management for better navigation flow
- Enable browser back/forward support for invoice actions
- Preserve tab and invoice selection across page refreshes
- Streamline invoice management workflow with persistent URLs

feat: improve invoice management UI and navigation

---

server/src/components/billing-dashboard/BillingCycles.tsx
server/src/lib/actions/billingCycleActions.ts
server/src/lib/billing/createBillingCycles.ts

Implement conflict detection when creating overlapping billing cycles
Enhance date validation and UTC handling in cycle calculations
Improve cycle creation error handling with retry capabilities
👑 "When the White Rabbit's schedule conflicted, even the Queen of Hearts knew: 'Off with the old date! Let the new one be never late!' Now your billing cycles stay timely, just like tea time – always at 6!" 🐰

feat(billing): Add date conflict resolution for billing cycles

---

server/src/components/time-management/TimeEntryEditForm.tsx
server/src/components/ui/TimePicker.tsx
server/src/types/ui-reflection/types.ts

Show validation errors only on save attempt
Clear errors when making changes
Use actual time difference for duration display
Maintain billable state during invalid entries
Ensure minimum billable duration of 1 minute
Consistent visual style with other components
Type-safe immutable updates
Better validation timing and feedback
Simplified billable duration logic
Flexible time entry with validation on save
Pay no attention to that bug behind the curtain! 🧙‍♂️✨

refactor(TimeEntryEditForm): improve validation and duration handling

---

server/next.config.mjs

This commit adds dotenv configuration to the Next.js config file, enabling environment variables to be loaded with the override option. This ensures that environment variables from .env files take precedence over existing environment variables.

feat: configure dotenv with override option

---

server/src/components/projects/TaskEdit.tsx
server/src/components/projects/TaskForm.tsx
server/src/components/time-management/ManagerApprovalDashboard.tsx
server/src/components/time-management/TimePeriodList.tsx
server/src/components/time-management/TimeSheet.tsx
server/src/interfaces/dataTable.interfaces.ts
server/src/interfaces/workItem.interfaces.ts
server/src/lib/actions/initializeApp.ts

We have some drawers there, but they are still wonky...

Time sheet

---

docs/billing.md
server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/lib/actions/companyBillingPlanActions.ts
server/src/lib/actions/invoiceActions.ts

Adds ability to preview invoices before finalization, helping users validate charges and prevent billing errors.
Key changes:
- Add invoice preview documentation and architecture
- Implement previewInvoice action that calculates without persistence
- Add preview button and modal UI to AutomaticInvoices component
- Rename "generate" to "finalize" for clearer invoice workflow
- Improve error handling in billing plan actions
- Update billing dashboard navigation
The preview system allows users to:
- View complete invoice calculations before committing
- Validate charges, taxes and adjustments
- Prevent billing errors through early verification
🐛 'How do you like your invoices?' 'Not at all!' said Alice. 'That's why we added previews!'

feat: Add invoice preview system for billing cycles

---

server/src/components/billing-dashboard/InvoiceTemplateManager.tsx
server/src/components/billing-dashboard/InvoiceTemplates.tsx
server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/TemplateRenderer.tsx
server/src/interfaces/invoice.interfaces.ts
server/src/lib/actions/invoiceActions.ts
server/src/utils/sampleInvoiceData.ts

- Add template name input field and improve form layout
- Implement loading state for template saving
- Update TemplateRenderer to use InvoiceViewModel directly instead of fetching
- Enhance sample invoice data with more detailed structure
- Make template parsing optional and validate before saving
- Add onTemplateUpdate handler for better state management
- Fix clone template button visibility
- Update interface definitions for better type safety

refactor: enhance invoice template management and rendering

---

docs/invoice_finalization.md
server/migrations/20250129214635_create_audit_logs.cjs
server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/TemplateRenderer.tsx
server/src/lib/actions/invoiceActions.ts
server/src/lib/db/index.tsx
server/src/lib/jobs/handlers/generateInvoiceHandler.ts
server/src/lib/jobs/handlers/invoiceZipHandler.ts
server/src/lib/logging/auditLog.ts
server/src/lib/models/invoice.ts
server/src/services/pdf-generation.service.ts
server/src/test/infrastructure/billingInvoiceGeneration.test.ts
server/src/test/infrastructure/prepaymentInvoice.test.ts

This commit implements a comprehensive invoice finalization system to maintain data integrity and provide clear audit trails. Key changes include:
- Add new finalization system with finalized_at timestamp tracking
- Implement separate displays for draft vs finalized invoices
- Add data protection to prevent modifications of finalized invoices
- Create audit logging system for tracking finalization state changes
- Add finalize/unfinalize server actions with proper authorization checks
- Update PDF generation to finalize invoices on download
- Add tenant context management for proper multi-tenancy support
- Update tests to reflect new invoice finalization flow
- Add documentation for the invoice finalization system
- Rename finalizeInvoice to generateInvoice for clarity
- Update …

feat: Add invoice finalization system

---

docs/client_portal_plan.md
docs/overview.md
server/src/app/api/files/[fileId]/download/route.ts
server/src/lib/actions/document-actions/documentActions.ts
server/src/lib/actions/file-actions/fileActions.ts
server/src/lib/actions/job-actions/scheduleInvoiceEmailAction.ts
server/src/lib/actions/job-actions/scheduleInvoiceZipAction.ts
server/src/lib/actions/useRegister.tsx
server/src/lib/eventBus/subscribers/ticketEmailSubscriber.ts
server/src/lib/jobs/handlers/invoiceEmailHandler.ts
server/src/lib/jobs/handlers/invoiceZipHandler.ts
server/src/lib/jobs/index.ts
server/src/lib/jobs/jobScheduler.ts
server/src/lib/notifications/email.ts
server/src/lib/notifications/sendEventEmail.ts
server/src/lib/storage/StorageService.ts
server/src/services/emailService.ts
server/src/services/job.service.ts

This commit consolidates and improves email handling across the application while enhancing job processing capabilities:
Email Service Changes:
- Migrate from utils/email/emailService.tsx to services/emailService.ts
- Implement robust email service with better error handling and logging
- Add support for templated emails with standardized interface
- Improve email configuration management with fallback options
Job Service Improvements:
- Refactor JobService to support step-by-step progress tracking
- Add detailed job status updates with human-readable descriptions
- Implement better error handling and context preservation
- Add support for immediate, scheduled, and recurring jobs
Related Changes:
- Update all email service imports across the codebase
- Improve invoice email handling with …

refactor: consolidate email services and enhance job handling

---

server/migrations/20250202005644_add_jobs_rls_policy.cjs
server/src/components/companies/CompanyPicker.tsx
server/src/components/contacts/Contacts.tsx
server/src/components/contacts/QuickAddContact.tsx
server/src/lib/actions/contact-actions/contactActions.tsx

Added comprehensive input validation, error boundaries, and user feedback in QuickAddContact component. Enhanced CompanyPicker interaction logic to prevent unintended closures and selection changes. Implemented detailed error handling in contact actions with specific error codes for client handling.
"Now we're following the White Rabbit down the validation hole! 🐇"

✨ Improve contact form validation and error handling

---

server/src/components/assets/CreateAssetDialog.tsx
server/src/components/billing-dashboard/ManualInvoices.tsx
server/src/components/billing-dashboard/PrepaymentInvoices.tsx
server/src/components/billing-dashboard/UsageTracking.tsx
server/src/components/companies/CompanyPicker.tsx
server/src/components/contacts/ContactDetailsEdit.tsx
server/src/components/projects/ProjectDetailsEdit.tsx
server/src/components/tickets/QuickAddTicket.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/time-management/time-entry/time-sheet/WorkItemPicker.tsx

Standardized company ID handling across billing/invoice components Transitioned from empty strings to null for unselected states Added proper type guards for company ID payloads
Enhanced CompanyPicker UI constraints
"Nothing comes from nothing" whispered the Cheshire Cat 🐱 as our null checks vanished into type-safe oblivion!

🔧 Improve null safety in company selection flows

---

package.json
server/Dockerfile
server/package.json
server/src/scripts/validateEnvStartup.ts

- fixed docker build to include tsconfig.base.json
- optimized docker build
- fixed startup js vs ts module issue

fix: fixed docker build / missing tsconfig.base.json / optimizations

---

docs/AI_coding_standards.md
package-lock.json
server/migrations/20250208103014_update_invoice_date_columns.cjs
server/migrations/20250208104756_update_company_billing_cycles_date_columns.cjs
server/migrations/20250208153014_update_invoice_date_columns.cjs
server/migrations/20250208153338_update_billing_date_columns.cjs
server/migrations/20250208154756_update_company_billing_cycles_date_columns.cjs
server/package.json
server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/TemplateRendererCore.ts
server/src/components/billing-dashboard/TimePeriodForm.tsx
server/src/components/billing-dashboard/TimePeriods.tsx
server/src/interfaces/invoice.interfaces.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/manualInvoiceActions.ts
server/src/lib/billing/billingEngine.ts
server/src/lib/billing/createBillingCycles.ts
server/src/lib/models/invoice.ts
server/src/lib/timePeriodSuggester.ts
server/src/lib/utils/dateTimeUtils.ts
server/src/test/unit/templateRenderer.test.tsx
server/src/test/unit/timePeriodSuggester.test.ts
server/src/utils/sampleInvoiceData.ts

This commit introduces a major update to date handling across the application:
- Replace JavaScript Date objects with Temporal API for consistent date handling
- Add new dateTimeUtils functions for date conversion and manipulation
- Update database date columns to use proper date types for business dates
- Add new migrations for converting date columns in billing-related tables
- Update billing engine and invoice generation to use Temporal dates
- Fix time period calculation to use start dates for period settings
- Add comprehensive tests for date handling edge cases
- Maintain timestamptz for audit fields while using date for business dates
Key improvements:
- Better timezone handling through Temporal API
- Clearer distinction between business dates and timestamps
- More reliable date …

feat: Migrate date handling to Temporal API for better timezone handling

---

server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/TimePeriodForm.tsx
server/src/components/billing-dashboard/TimePeriods.tsx
server/src/components/time-management/approvals/ManagerApprovalDashboard.tsx
server/src/components/time-management/time-entry/TimePeriodList.tsx
server/src/components/time-management/time-entry/TimeTracking.tsx
server/src/interfaces/timeEntry.interfaces.ts
server/src/lib/actions/timeEntryActions.ts
server/src/lib/actions/timePeriodsActions.ts

Fixes compilation issues by introducing ITimePeriodView to handle string date representations in the UI while maintaining Temporal.PlainDate in the model layer. Updates related components and actions to properly convert between model and view types when passing data between layers.

refactor: update time period types to separate model and view interfaces

---

docs/api_overview.md
docs/customer_provisioning_api.md

Add comprehensive documentation for the new MSP PSA enterprise Provisioning API:
- api_overview.md: Detailed technical design including architecture, security, file structure, and integration details
- customer_provisioning_api.md: API specifications, endpoints, and data validation requirements
The documentation outlines a Next.js-based REST API system for partner integrations to provision customer accounts in the enterprise edition.

docs: add Provisioning API design and documentation

---

Dockerfile.prod
docker-compose.prebuilt.base.yaml
docker-compose.prebuilt.ce.yaml
docker-compose.prebuilt.yaml
server/docker-compose.prebuilt.yaml

Add Docker configuration files for prebuilt deployments:
- Copy server setup scripts to production image
- Add docker-compose.prebuilt.base.yaml with shared environment and base services
- Add docker-compose.prebuilt.ce.yaml for community edition deployment
- Add docker-compose.prebuilt.yaml for full deployment configuration
- Add server-specific prebuilt Docker compose configuration
These changes enable deployment of prebuilt Docker images with proper environment configuration and setup scripts for both community and full editions.

feat: add prebuilt Docker configuration and setup scripts

---

server/src/components/schedule/EntryPopup.tsx
server/src/components/ui/ConfirmationDialog.tsx
server/src/components/ui/Dialog.tsx

- Making dialog widths more flexible with dynamic class names
- Allowing custom sizing through className props
- Adding proper constraints for recurrence dialog
🌈 "We're all mad here!" said the Cheshire Cat as dialogs now properly resize like Alice's wonderland cakes 🍄

Enhance UI consistency by:

---

server/src/lib/actions/workItemActions.ts

Ensure all GROUP BY clauses include tenant context Add explicit tenant checks in JOIN conditions
Update array membership checks to use proper SQL syntax Fix missing group-by fields that could cause indeterminate results 
"Follow the yellow tenant road... 🧙 to the emerald city of data isolation!" 🌪️

✨ Tighten tenant isolation in work item queries

---

server/src/components/time-management/time-entry/time-sheet/AddWorkItemDialog.tsx
server/src/components/time-management/time-entry/time-sheet/TimeSheet.tsx
server/src/components/time-management/time-entry/time-sheet/WorkItemPicker.tsx
server/src/components/time-management/time-entry/time-sheet/types.ts

Added validation to ensure ad-hoc work items stay within current billing period constraints. Implemented date range checks with user-friendly error messaging and visual indicators when dates fall outside allowed period. No more wandering off the yellow brick road of billing compliance! 🧭⏳✅
"Stay within the Emerald City's billing borders, Dorothy! 🧙♂️💚"

🔒 Enforce time period boundaries in work item entry

---

server/src/components/projects/TaskForm.tsx

✨ Added project boundary detection and status handling logic
📦 Let backend service handle status transitions during project moves
✅ Updated form state management for checklist items and assignments
"Follow the yellow brick road of project boundaries! 🧙➡️🏰"

🔀 Improve cross-project task movement with dynamic status mapping

---

server/src/components/projects/ProjectDetailsEdit.tsx
server/src/components/settings/general/TicketingSettings.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/ui/CustomSelect.tsx
server/src/interfaces/index.ts
server/src/interfaces/project.interfaces.ts
server/src/interfaces/status.interface.ts
server/src/interfaces/ticket.interfaces.tsx
server/src/lib/actions/project-actions/projectActions.ts
server/src/lib/actions/status-actions/statusActions.ts
server/src/lib/actions/ticket-actions/ticketActions.ts
server/src/lib/models/project.ts
server/src/lib/models/status.ts
server/src/lib/schemas/ticket.schema.ts

Refactored status interfaces into dedicated module to reduce circular dependencies 
Added unified 'open' default filter state with visual indicators for closed statuses 
Implemented smart status filtering that respects both custom and system-defined states 
Improved type safety across project/ticket management components 
"The code tornado has landed! 🌪️ Now following the yellow brick road to cleaner type definitions and happier filtering. No more flying monkeys in our status management!" 🧙

🔧 Centralize status management and enhance ticket filtering

---

server/src/components/schedule/EntryPopup.tsx
server/src/components/time-management/time-entry/time-sheet/WorkItemPicker.tsx

Remove hardcoded timePeriod construction in schedule entry popup Add context-aware date range handling in timesheet components Fix incorrect date initialization when outside timesheet context No more date range mixups - you're not in Kansas anymore! 🌪️

📝 Improve work item date range initialization logic

---

docs/AI_coding_standards.md
server/knexfile.cjs
server/src/app/actions/cleanupAction.ts
server/src/lib/actions/contact-actions/contactActions.tsx
server/src/lib/db/admin.ts
server/src/lib/db/db.tsx
server/src/lib/db/knexfile.tsx
server/src/lib/eventBus/initialize.ts
server/src/lib/models/company.tsx
server/src/lib/models/contact.tsx

- Enhance tenant isolation by using connection pools with proper tenant context
- Replace raw tenant strings with proper tenant column joins
- Fix tenant context propagation in distributed queries
- Add tenant filtering to model queries for better security
- Clean up whitespace and formatting in contact actions
- Update admin connection to use structured config
- Refactor connection management to use Map instead of plain object
- Add AsyncLocalStorage for tenant context tracking
- Update documentation with distributed query tenant requirements
- protect tenant

refactor: improve multi-tenant database handling and security

---

server/src/components/companies/CompanyPicker.tsx

- Set responsive width constraints to prevent overflow issues
- Increase max height for better browsing with large company lists
- Add minimum width to maintain readability
- Adjust positioning for consistent visual hierarchy
The dropdown now grows to fit content yet stays contained - no more wandering through Wonderland's endless fields! 🌻
🌈 There's no place like a well-formatted component!

Improve company dropdown layout and scrollability 🎩

---

server/src/lib/utils/getSecret.ts
server/src/test/infrastructure/billingInvoiceGeneration.test.ts
server/src/test/infrastructure/companyBillingCycle.test.ts
server/src/test/infrastructure/manualInvoice.test.ts
server/src/test/infrastructure/prepaymentInvoice.test.ts
server/src/test/infrastructure/projectManagement.test.ts
server/src/test/infrastructure/projectPermissions.test.ts
server/src/test/infrastructure/ticketPermissions.test.ts
server/src/test/infrastructure/timePeriods.test.ts
server/src/test/infrastructure/timePeriodsActions.test.ts
server/test-utils/dateUtils.ts
server/test-utils/dbConfig.ts
server/test-utils/dbReset.ts
server/test-utils/errorUtils.ts
server/test-utils/testContext.ts
server/test-utils/testDataFactory.ts
server/test-utils/testMocks.ts

- Introduce comprehensive test utilities:
- Add TestContext for managing test state and dependencies
- Create date helper functions for consistent date handling
- Add error assertion utilities for consistent error testing
- Implement test data factory for creating test entities
- Add mock utilities for Next.js and auth components
- Refactor test files to use new test infrastructure:
- Standardize test setup and teardown
- Remove duplicate boilerplate code
- Centralize database connection management
- Improve test isolation and cleanup
- Improve test maintainability:
- Add type safety to test data creation
- Centralize test configuration
- Add helper functions for common test patterns
- Standardize error handling and assertions
This refactor makes tests more maintainable, type-safe and …

refactor(tests): standardize test infrastructure and add test utilities

---

.gitignore
server/seeds/dev/06_channels.cjs
server/seeds/dev/07_statuses.cjs
server/src/components/client-portal/tickets/TicketList.tsx
server/src/components/tickets/CommentItem.tsx

Added default channel/status flags in seeds for clearer initial setup Streamlined ticket status updates with inline dropdowns 🎚️ Introduced prominent "Create Ticket" CTA button (+1.5x engagement) Unified icon library usage (lucide-react) across components Removed redundant actions column for cleaner interface "Off to see the wizard" of polished user experiences! 🌪️👠

🔧 Enhance client portal UX and data seeding logic

---

server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/ManualInvoices.tsx
server/src/lib/actions/invoiceActions.ts

- Rename "Manage Items" to "Invoice Details" for consistent terminology
- Add ability to edit invoice numbers for existing invoices
- Display company name in invoice details view
- Add unique constraint validation for invoice numbers
- Improve button styling and error handling
- Remove auto-navigation after save to allow reviewing changes
"🐰 'Your invoice number is unique, just like you,' said the White Rabbit, checking his pocket watch nervously"

refactor: improve invoice management UI and number editing

---

server/seeds/dev/71_tax_rates.cjs
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/manualInvoiceActions.ts
server/src/lib/actions/taxSettingsActions.ts
server/src/lib/services/taxService.ts
server/src/test/infrastructure/billingInvoiceGeneration.test.ts
server/src/test/infrastructure/invoiceDueDate.test.ts
server/src/test/infrastructure/manualInvoice.test.ts
server/src/test/infrastructure/taxExemptionHandling.test.ts

Add comprehensive tax and invoice handling improvements:
- Add US-FL tax rate seed data with 6% rate to demo seed data
- Refactor tax settings into dedicated TaxService class
- Export getDueDate function for broader usage
- Add error handling for invalid service IDs in manual invoices
- Add extensive test coverage for:
- Invoice due date calculations
- Tax exemption handling
- Billing invoice generation with subtotals
- Manual invoice generation
The changes improve reliability and testability of the billing system.

feat(billing): Enhance tax handling and invoice generation

---

docs/billing.md
server/src/lib/actions/manualInvoiceActions.ts
server/src/lib/services/taxService.ts
server/src/test/infrastructure/billingInvoiceGeneration.test.ts
server/src/test/infrastructure/manualInvoice.test.ts

feat(billing): improve tax calculation and allocation for invoices
This commit implements a comprehensive tax calculation and allocation strategy
that follows standard accounting practices:
- Calculate tax on net invoice subtotal after all discounts/adjustments
- Distribute tax proportionally among positive line items only
- Process items consistently (highest to lowest amount)
- Use Math.floor for tax distribution except last item
- Update billing.md with detailed tax calculation documentation
- Add test cases for mixed positive/negative line items
This ensures accurate tax handling for discounts, refunds, and mixed scenarios
while maintaining precise tax allocation across line items.
🍄 'One tax makes you larger, and one tax makes you small, but the ones that proportionally distribute …

feat(billing): improve tax calculation and allocation for invoices

---

docs/tax_calculation_allocation.md
server/migrations/20250224084007_set_tax_amount_to_bigint.cjs
server/src/lib/actions/invoiceActions.ts
server/src/test/infrastructure/billingInvoiceGeneration.test.ts
server/src/test/infrastructure/taxRateChanges.test.ts
server/src/test/infrastructure/taxRoundingBehavior.test.ts

- Add comprehensive tax calculation documentation
- Modify tax calculation to only apply to positive net amounts
- Group invoice items by tax region for accurate tax calculation
- Implement proportional tax allocation within tax regions
- Add tests for various tax scenarios:
- Credit notes (negative amounts)
- Tax exempt scenarios
- Mixed positive/negative amounts
- Multi-region tax calculations
- Fix rounding issues by using Math.floor for intermediate calculations
"🌪️ Toto, I've a feeling we're not calculating taxes randomly anymore... now we're actually doing it properly! 🐕"

refactor: Refactor tax calculation and allocation for invoices

---

docs/billing.md
server/migrations/20250225214222_add_credit_issuance_from_negative_invoice_type.cjs
server/src/interfaces/billing.interfaces.ts
server/src/lib/actions/creditActions.ts
server/src/lib/actions/invoiceActions.ts
server/src/test/infrastructure/creditApplication.test.ts
server/src/test/infrastructure/negativeInvoiceCredit.test.ts
server/src/test/infrastructure/prepaymentInvoice.test.ts

This commit updates the billing documentation to reflect the actual implementation of the credit system and tax calculation strategy. It also adds functionality to automatically create credits from negative invoices when they are finalized.
The key changes include:
- Updated tax calculation documentation to accurately reflect the pre-discount basis
- Added documentation for all 5 service types (Fixed, Time, Usage, Product, License)
- Added comprehensive credit system documentation and transaction types
- Implemented negative invoice credit generation with proper transaction tracking
- Added database migration for new 'credit_issuance_from_negative_invoice' transaction type
- Created extensive test suite for negative invoice credit functionality
- Fixed existing tests to work with the …

# Credit enhancements and documentation update

---

server/src/lib/actions/creditActions.ts
server/src/test/infrastructure/creditApplication.test.ts

Refactored the credit handling system to safely apply available credit to invoices. Key improvements:
- Prevents negative credit balances by checking company's actual available credit
- Moved credit balance check logic inside conditional block to prevent unnecessary database queries
- Added safeguards to only apply the amount of credit that is actually available
- Improved credit balance tracking with direct updates to company records
- Enhanced logging for better transaction visibility
- Added comprehensive tests for various credit application scenarios:
- Multiple invoice payment with full credit coverage
- Partial credit application across multiple invoices
- Edge cases around credit availability
These changes improve the reliability of the billing system by ensuring credit is never …

Improved credit balance handling and invoice payment flow

---

docs/billing.md
docs/credits_and_reconciliation.md
server/migrations/20250227133900_create_credit_reconciliation_reports.cjs
server/migrations/20250227135400_add_metadata_to_credit_reconciliation_reports.cjs
server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/CreditReconciliation.tsx
server/src/components/billing-dashboard/DiscrepancyDetail.tsx
server/src/components/billing-dashboard/RecommendedFixPanel.tsx
server/src/components/billing-dashboard/ReconciliationResolution.tsx
server/src/interfaces/billing.interfaces.ts
server/src/lib/actions/creditActions.ts
server/src/lib/actions/creditReconciliationActions.ts
server/src/lib/actions/creditReconciliationFixActions.ts
server/src/lib/actions/reconciliationReportActions.ts
server/src/lib/jobs/handlers/creditReconciliationHandler.ts
server/src/lib/jobs/index.ts
server/src/lib/jobs/initializeScheduledJobs.ts
server/src/lib/models/creditReconciliationReport.ts

Add a comprehensive credit reconciliation system to ensure the integrity of credit balances by detecting and reporting discrepancies between expected and actual credit balances. This system follows a philosophy of separating detection from correction, providing transparency for all financial operations.
The implementation includes:
- New database tables for tracking reconciliation reports
- Detection mechanisms for balance discrepancies and credit tracking issues
- User interface components for managing and resolving discrepancies
- Server actions for validation and resolution
- Detailed documentation of the reconciliation philosophy and process
- Scheduled validation jobs that run daily
This commit also refactors existing credit validation logic to work with the new reconciliation system …

# feat(billing): add credit reconciliation system

---

docs/workflow/task-inbox-integration.md
server/src/app/msp/user-activities/page.tsx
server/src/components/user-activities/ActivitiesDataTable.tsx
server/src/components/user-activities/ActivitiesDataTableSection.tsx
server/src/components/user-activities/ActivityActionMenu.tsx
server/src/components/user-activities/ActivityCard.tsx
server/src/components/user-activities/ActivityDetailsDrawer.tsx
server/src/components/user-activities/ActivityFilters.tsx
server/src/components/user-activities/ProjectsSection.tsx
server/src/components/user-activities/ScheduleSection.tsx
server/src/components/user-activities/TicketsSection.tsx
server/src/components/user-activities/UserActivitiesDashboard.tsx
server/src/components/user-activities/WorkflowTaskListDrawer.tsx
server/src/components/user-activities/WorkflowTasksSection.tsx
server/src/config/menuConfig.ts
server/src/context/DrawerContext.tsx
server/src/interfaces/activity.interfaces.ts
server/src/lib/actions/activity-actions/activityAggregationActions.ts
server/src/lib/actions/activity-actions/activityServerActions.ts
server/src/lib/actions/activity-actions/activityStatusActions.ts
server/src/lib/actions/activity-actions/workflowTaskActions.ts

Add comprehensive user activities management interface with dual viewing modes:
- Create dedicated /msp/user-activities route with authentication checks
- Implement ActivitiesDataTable with sorting and filtering capabilities
- Add table view option alongside existing card view in UserActivitiesDashboard
- Enhance DrawerContext with history navigation and specialized drawer types
- Create workflow task list drawer with advanced filtering and sorting
- Update menu configuration to include User Activities entry
This update provides MSP users a more efficient way to manage and track activities through both card and tabular interfaces with consistent styling and functionality.
"Begin at the beginning," the King said, "and continue through the DrawerContext history, till you come to the end: …

feat(user-activities): add user activities page with data table view

---

docs/workflow/integration-patterns.md
docs/workflow/workflow-patterns.md
docs/workflow/workflow-system.md
server/migrations/20250308144800_create_workflow_template_tables.cjs
server/src/lib/actions/workflow-runtime-actions.ts
shared/workflow/core/workflowDefinition.ts
shared/workflow/core/workflowRuntime.ts
shared/workflow/init/workflowRegistration.ts

Add support for storing and loading workflow definitions from the database, enabling dynamic workflow registration without code changes.
- Create database schema for workflow templates, registrations, and versioning
- Implement serialization/deserialization of workflow functions
- Add server actions for workflow template management and registration
- Modify workflow runtime to load definitions from database on-demand
- Update registration system to support both code and database-defined workflows
This change maintains backward compatibility with existing code-defined workflows while enabling a more flexible approach through database storage.
"Curiouser and curiouser! Our workflows have eaten the 'STORE ME IN DATABASE' cake and grown so flexible they can touch their toes!" 🎂

feat(workflow): implement database-driven workflow registration

---

docs/workflow/typescript-workflow-creation.md
docs/workflow/workflow-system.md
server/src/components/automation-hub/Workflows.tsx
server/src/components/workflow-editor/TestWorkflowModal.tsx
server/src/components/workflow-editor/WorkflowEditorComponent.tsx
server/src/lib/actions/workflow-editor-actions.ts
server/src/lib/actions/workflow-event-actions.ts
server/src/lib/actions/workflow-event-attachment-actions.ts
server/src/lib/actions/workflow-runtime-actions.ts

Add comprehensive workflow testing capabilities with a user-friendly modal interface for triggering workflow executions with custom events. The new system allows developers to:
- Test workflows directly from the workflow list or editor
- Simulate event triggers with custom payloads
- Examine event schema information for proper payloads
- Auto-generate example data based on schemas
- Monitor workflow executions triggered by tests
- Added TestWorkflowModal component with a complete UI for testing workflows
- Implemented executeWorkflowTest action to run temporary workflow instances
- Enhanced workflow event system to support both direct execution and event bus publishing
- Improved workflow documentation to clarify event handling patterns
- Added workflow activation/deactivation toggle in …

feat(workflow): add workflow testing functionality with event simulation

---

package-lock.json
server/seeds/dev/74_workflow_registrations.cjs
server/src/components/workflow-editor/WorkflowEditor.tsx
server/src/lib/db/admin.ts
services/workflow-worker/src/WorkflowWorker.ts
shared/db/admin.ts
shared/package.json
shared/workflow/core/formRegistry.ts
shared/workflow/core/formValidationService.ts
shared/workflow/core/taskInboxService.ts
shared/workflow/persistence/formDefinitionModel.ts
shared/workflow/persistence/formSchemaModel.ts
shared/workflow/persistence/taskInboxInterfaces.ts

Add validation libraries and improve workflow editor components:
- Add AJV and related format libraries for JSON schema validation
- Add dotenv to workflow-worker for environment configuration
- Fix ESM imports by adding .js extensions to imported modules
- Improve type safety in WorkflowWorker with proper type casting
- Add JSDoc documentation to invoice approval workflow
- Simplify form validation service with dynamic imports
- Clean up console logging in database connection code
- Update workflow editor example to use log_audit_message action
This ensures form validation works properly across the application and fixes ESM module resolution issues in the workflow system.

feat(workflow): enhance validation and fix module imports

---

server/src/components/automation-hub/Workflows.tsx
server/src/components/user-activities/ActivitiesDataTable.tsx
server/src/components/user-activities/ActivitiesDataTableSection.tsx
server/src/components/user-activities/ActivityActionMenu.tsx
server/src/components/user-activities/ActivityDetailsDrawer.tsx
server/src/components/user-activities/UserActivitiesDashboard.tsx
server/src/components/user-activities/WorkflowTasksSection.tsx
server/src/components/workflow/TaskForm.tsx
server/src/components/workflows/WorkflowExecutionsTable.tsx
server/src/components/workflows/logs-history/LogsHistoryWorkflowTable.tsx
server/src/lib/actions/workflow-actions/taskInboxActions.ts
shared/workflow/core/actionRegistry.ts
shared/workflow/core/taskInboxService.ts
shared/workflow/core/workflowRuntime.ts
shared/workflow/init/registerWorkflowActions.ts
shared/workflow/init/workflowInit.ts
shared/workflow/persistence/workflowTaskModel.ts

- Add workflow task testing functionality with button in table view.
- Implement activity details drawer for task forms and workflow details.
- Improve user experience by persisting view mode preferences.
- Fix task creation with proper JSON array handling for assigned roles/users.
- Add workflow form actions for better form management integration.
- Optimize task submission with better error handling and execution state loading.

feat(workflows): enhance workflow UI and task management

---

server/src/components/tickets/TicketDetails.tsx
server/src/components/tickets/TicketProperties.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/time-management/interval-tracking/IntervalItem.tsx
server/src/components/time-management/interval-tracking/IntervalManagement.tsx
server/src/components/time-management/interval-tracking/IntervalManagementDrawer.tsx
server/src/components/time-management/interval-tracking/IntervalSection.tsx
server/src/components/time-management/interval-tracking/utils.ts
server/src/components/time-management/time-entry/time-sheet/TimeEntryDialog.tsx
server/src/components/time-management/time-entry/time-sheet/TimeSheet.tsx
server/src/components/time-management/time-entry/time-sheet/TimeSheetHeader.tsx
server/src/hooks/useIntervalTracking.ts
server/src/hooks/useTicketTimeTracking.ts
server/src/interfaces/timeEntry.interfaces.ts
server/src/lib/models/timePeriodSettings.ts
server/src/services/IntervalTrackingService.ts
server/src/types/interval-tracking.ts

This commit adds a comprehensive time tracking feature that automatically records the time users spend viewing tickets. The system uses IndexedDB to store time intervals locally and provides UI components to manage these intervals.
Key features:
- Automatic time tracking when viewing tickets
- Interval management interface in ticket details and dashboard
- Ability to convert tracked time intervals into billable time entries
- Support for merging, filtering, and organizing time intervals
- Auto-closing of intervals when tabs are closed or switching contexts
The implementation includes:
- `IntervalTrackingService` for handling IndexedDB storage
- React hooks for tracking time (`useTicketTimeTracking` and `useIntervalTracking`)
- UI components for displaying and managing intervals
- …

feat(time-tracking): implement automatic interval tracking for tickets

---

server/src/components/companies/Companies.tsx
server/src/components/projects/PhaseListItem.tsx
server/src/components/projects/ProjectQuickAdd.tsx
server/src/components/technician-dispatch/TechnicianDispatchDashboard.tsx
server/src/components/tickets/TicketDetails.tsx
server/src/lib/actions/companyActions.ts
server/src/lib/actions/workItemActions.ts
server/src/lib/models/scheduleEntry.ts

This commit adds several important UI enhancements as part of our road to release:
- Add confirmation dialogs for company deletion to prevent accidental data loss
- Improve user feedback with toast notifications in ProjectQuickAdd workflow
- Enhance TechnicianDispatchDashboard with filtering capabilities for better workflow
- Fix critical issues in ticket time entry handling with proper time period dialogs
- Update company deletion logic to correctly handle document associations
- Add phase description display in project views for better information hierarchy
- Optimize schedule entry handling for various work item types
These changes address several UX issues identified during pre-release testing and ensure a more polished, production-ready experience.
> 🧙‍♂️ "Toto, I've a feeling we're …

feat(ui): improve user experience for production release

---

server/src/components/TaxSettingsForm.tsx
server/src/components/companies/CompanyDetails.tsx
server/src/components/companies/CompanyForm.tsx
server/src/components/documents/DocumentSelector.tsx
server/src/components/documents/DocumentStorageCard.tsx
server/src/components/documents/Documents.tsx
server/src/interfaces/document.interface.tsx
server/src/lib/actions/companyActions.ts
server/src/lib/actions/document-actions/documentActions.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/taxSettingsActions.ts
server/src/lib/models/document.tsx
server/src/lib/models/interactions.ts

This comprehensive update fixes multiple critical issues in company functionality:
- fix(interactions): remove incorrect SQL join condition in interactions.ts that was preventing all interaction functionality
- fix(documents): add validation for required props in DocumentSelector to prevent client-side exceptions
- fix(company): improve nested property updates and synchronize website fields in company profiles
- fix(billing): use getAllTemplates() to fetch both standard and tenant-specific invoice templates
- fix(documents): increase drawer width to accommodate document editor fields
- fix(tax): improve error handling and state management in tax settings updates
- fix(notes): add creation date display to notes
🐰 "Curiouser and curiouser!" cried Alice, as the bugs vanished down the rabbit …

fix: resolve critical issues in company management features for release

---

server/src/app/msp/documents/page.tsx
server/src/components/documents/DocumentStorageCard.tsx
server/src/components/documents/Documents.tsx
server/src/lib/actions/document-actions/documentActions.ts

This commit fixes several critical bugs in the document management system:
1. **Document Filter Handling**:
- Fixes empty state handling in filters
- Addresses race conditions by executing searches directly instead of relying on state updates
- Implements proper filter clearing functionality
- Adds placeholder support for document type filtering
2. **Document Deletion Safety**:
- Adds confirmation dialogs for document deletion and disassociation
- Prevents event bubbling when clicking action buttons in document cards
- Fixes database foreign key issues by properly clearing references before deletion
3. **Document Search Performance**:
- Optimizes database queries by adding conditional joins
- Implements case-insensitive search
- Improves MIME type filtering with more precise conditions
- …

fix(documents): improve document filtering and add confirmation dialogs

---

server/src/app/msp/tickets/[id]/TicketDetailsContainer.tsx
server/src/components/interactions/InteractionsFeed.tsx
server/src/components/interactions/OverallInteractionsFeed.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/tickets/TicketingDashboardContainer.tsx
server/src/lib/models/project.ts

This changeset improves the ticketing system in two key ways:
1. Authentication Improvement: Replaces direct session.user usage with explicit calls to getCurrentUser() throughout ticket-related components, ensuring more reliable user context retrieval.
2. Filter State Enhancement:
- Changes default filter values from empty strings to 'all' for better semantics
- Implements comprehensive filter persistence when loading more tickets
- Enhances ticket filtering logic with a consolidated approach that applies all filters simultaneously
The changes also include a SQL join fix in the project model that ensures proper tenant isolation when joining the companies table.

feat(tickets): v0.5.0 smoke test fixes

---

server/src/components/projects/KanbanBoard.tsx
server/src/components/projects/ProjectDetail.tsx
server/src/components/projects/StatusColumn.tsx
server/src/components/projects/TaskCard.tsx
server/src/components/projects/TaskEdit.tsx
server/src/components/projects/TaskForm.tsx
server/src/components/projects/TaskQuickAdd.tsx
server/src/components/projects/TaskTicketLinks.tsx
server/src/interfaces/project.interfaces.ts
server/src/lib/actions/project-actions/projectActions.ts
server/src/lib/models/projectTask.ts

Improve performance and reduce API calls by:
- Adding ticket links and resources as props to task components
- Enhancing KanbanBoard to enrich tasks with their associated data
- Implementing lazy loading for ticket links and resource data
- Using cached project tree data for task dialogs
- Maintaining data consistency across task operations
- Adding proper typing for ticket links and task resources

feat: optimize task data loading for kanban board and task dialogs

---

server/src/app/msp/billing/credits/AddCreditButton.tsx
server/src/app/msp/billing/credits/BackButton.tsx
server/src/app/msp/billing/credits/page.tsx
server/src/components/billing-dashboard/CreditManagement.tsx
server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/LineItem.tsx
server/src/components/billing-dashboard/ManualInvoices.tsx
server/src/components/billing-dashboard/ServiceCatalogManager.tsx
server/src/components/billing-dashboard/TimePeriodForm.tsx
server/src/components/billing-dashboard/UsageTracking.tsx
server/src/components/ui/DataTable.tsx
server/src/interfaces/invoice.interfaces.ts
server/src/lib/actions/creditActions.ts
server/src/lib/actions/job-actions/scheduleInvoiceEmailAction.ts
server/src/lib/actions/job-actions/scheduleInvoiceZipAction.ts
server/src/lib/actions/timePeriodsActions.ts
server/src/lib/services/invoiceService.ts
server/src/lib/timePeriodSuggester.ts
server/src/lib/utils/dateTimeUtils.ts

- Time Periods Tab: Fixed React warning by implementing reducer pattern for state updates
- Invoices Tab: Improved error handling, fixed discount UI anomaly, resolved rendering errors, enhanced PDF download error handling, added unfinalize option
- Service Catalog Tab: Removed spurious entries by showing type-specific columns
- Usage Tracking Tab: Eliminated edit dialog header duplication, fixed usage date update, added service filter reset
- Credits Tab: Fixed SQL error, improved UI navigation, implemented Add Credit functionality
All fixes have been verified and significantly improve user experience and functionality.

feat(billing-dashboard): complete bug fixes for Billing Dashboard

---

server/migrations/20250323194900_create_plan_bundles_tables.cjs
server/migrations/20250324103900_add_custom_rate_to_bundle_billing_plans.cjs
server/src/components/billing-dashboard/BillingDashboard.tsx
server/src/components/billing-dashboard/invoices/BundleInvoiceItems.tsx
server/src/components/billing-dashboard/plan-bundles/BundlePlanRateDialog.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundleDetail.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundleDialog.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundleForm.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundleHeader.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundlePlans.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundles.tsx
server/src/components/billing-dashboard/reports/BundlePerformance.tsx
server/src/components/billing-dashboard/reports/BundleUsageReport.tsx
server/src/components/companies/CompanyBundleAssignment.tsx
server/src/components/companies/CompanyBundleDialog.tsx
server/src/config/menuConfig.ts
server/src/interfaces/billing.interfaces.ts
server/src/interfaces/invoice.interfaces.ts
server/src/interfaces/planBundle.interfaces.ts
server/src/lib/actions/bundleBillingPlanActions.ts
server/src/lib/actions/companyPlanBundleActions.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/planBundleActions.ts
server/src/lib/billing/billingEngine.ts
server/src/lib/models/bundleBillingPlan.ts
server/src/lib/models/clientBilling.ts
server/src/lib/models/companyPlanBundle.ts
server/src/lib/models/planBundle.ts

- Added database schema changes for Plan Bundles (knex migration)
- Implemented core interfaces: IPlanBundle, IBundleBillingPlan, ICompanyPlanBundle
- Created model classes (PlanBundle, BundleBillingPlan, CompanyPlanBundle) with CRUD operations
- Added server actions for bundle, plan-to-bundle, and company-bundle management
- Updated billing engine to handle Plan Bundles (query optimization, calculations)
- Modified invoice generation to include bundle information and grouping
- Enhanced database access layer for bundle-aware operations
- Implemented frontend UI components for bundle management
- Added bundle assignment UI to company billing section
- Introduced bundle reporting and metrics components
- Updated sidebar menu with Plan Bundles section
This implementation provides named …

feat(billing): implement Plan Bundles for simplified billing management

---

server/src/components/billing-dashboard/BillingPlanDialog.tsx
server/src/components/billing-dashboard/InvoiceTemplates.tsx
server/src/components/billing-dashboard/ServiceCatalogManager.tsx
server/src/components/billing-dashboard/TaxRates.tsx
server/src/components/billing-dashboard/TimePeriods.tsx
server/src/components/billing-dashboard/UsageTracking.tsx
server/src/components/billing-dashboard/billing-plans/BillingPlanForm.tsx
server/src/components/billing-dashboard/billing-plans/BillingPlanServices.tsx
server/src/interfaces/planServiceConfiguration.interfaces.ts

- Fixed billing plan service management to allow multiple services per plan
- Ensured services are properly added when creating new billing plans
- Updated all tabs to use consistent DataTable component
- Implemented row click edit functionality across all tables
- Improved UI layout with proper spacing and alignment
- Added loading states and error handling for service additions

fix(billing-dashboard): resolve multiple UI and functionality issues

---

server/src/components/projects/ProjectDetailsEdit.tsx
server/src/components/projects/ProjectQuickAdd.tsx
server/src/components/settings/general/TeamDetails.tsx
server/src/components/settings/general/TeamList.tsx
server/src/components/tickets/QuickAddTicket.tsx
server/src/components/tickets/TicketDetails.tsx
server/src/components/tickets/TicketInfo.tsx
server/src/components/ui/AvatarIcon.tsx
server/src/components/ui/UserPicker.tsx

Replaced CustomSelect with UserPicker in ProjectDetailsEdit, ProjectQuickAdd, TeamDetails, TeamList, QuickAddTicket, and TicketInfo components Enhanced UserPicker with new props for better customization (labelStyle, buttonWidth, placeholder) Improved AvatarIcon to use consistent color generation based on userId Added inactive user state handling in UserPicker
Standardized user selection interface across the application These changes provide a more consistent and flexible user selection experience while reducing code duplication. The UserPicker now handles edge cases better and provides more visual feedback.
No more clicking ruby slippers to find users - we've got them all in one magical picker now! 🧙‍♂️✨

Refactor user selection components to use unified UserPicker 🎛️

---

server/src/components/client-portal/tickets/TicketDetails.tsx
server/src/components/editor/RichTextViewer.tsx
server/src/components/editor/TextEditor.tsx
server/src/components/tickets/CommentItem.tsx
server/src/components/tickets/TicketConversation.tsx
server/src/components/tickets/TicketInfo.tsx

Enhanced JSON parsing and empty block removal in RichTextViewer/TextEditor Tightened up spacing in ticket components for better visual hierarchy Added robust error handling for malformed content
Like the Cheshire Cat's grin, these changes make the editor more reliable while disappearing empty blocks 🐱✨"

Improve rich text editor content handling and ticket UI spacing

---

server/migrations/20250331174500_add_base_rate_to_fixed_plan_config.cjs
server/src/components/billing-dashboard/BillingPlans.tsx
server/src/components/billing-dashboard/FixedPlanServicesList.tsx
server/src/components/billing-dashboard/billing-plans/FixedPlanConfiguration.tsx
server/src/components/billing-dashboard/billing-plans/HourlyPlanConfiguration.tsx
server/src/components/billing-dashboard/billing-plans/UsagePlanConfiguration.tsx
server/src/interfaces/planServiceConfiguration.interfaces.ts
server/src/lib/actions/billingPlanAction.ts
server/src/lib/actions/planServiceActions.ts
server/src/lib/models/planServiceFixedConfig.ts
server/src/lib/services/planServiceConfigurationService.ts
server/tailwind.config.ts

This commit introduces a round of polish and refactoring across the billing plan configuration UI and backend logic for Fixed, Hourly, and Usage plans. The goal is to improve clarity, data consistency, and robustness while introducing specific enhancements.
Key improvements include:
- **Fixed Plan Configuration:**
- Introduced a dedicated `base_rate` field stored in `plan_service_fixed_config` (via migration).
- Created specific backend actions (`get/updateFixedPlanConfiguration`) for managing fixed plan settings (base rate, proration, alignment).
- Updated the `FixedPlanConfiguration` component to use these dedicated actions, separating concerns from general plan updates.
- **Data Handling & Consistency:**
- Optimized data fetching in `FixedPlanServicesList` by using …

refactor(plan-config): enhance billing plan configuration management

---

server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/CompanyBundleAssignment.tsx
server/src/components/companies/CompanyBundleDialog.tsx
server/src/lib/actions/companyPlanBundleActions.ts
server/src/lib/models/companyPlanBundle.ts

- Improve plan bundle assignment interface with better information display,
- fix backend model to return plan names, and update UI components for better UX.

feat(billing): enhance plan bundle UI components

---

package-lock.json
package.json
server/src/components/contacts/ContactPicker.tsx

Integrated AvatarIcon component into ContactPicker for better visual identification Implemented name parsing helper for consistent avatar display Aligned styling with UserPicker component
Now following the yellow brick road to more consistent UI components! 🧙‍♂️✨

feat(contacts): Add avatar support to ContactPicker

---

server/src/components/projects/TaskForm.tsx
server/src/components/tickets/TicketDetails.tsx
server/src/components/time-management/time-entry/time-sheet/TimeSheet.tsx
server/src/components/time-management/time-entry/time-sheet/WorkItemDrawer.tsx
server/src/lib/actions/project-actions/projectTaskActions.ts
server/src/lib/actions/timeEntryActions.ts

- Improve time sheet UI components for better drawer integration
- Fix React dependency warnings in components
- Prevent task deletion when time entries exist
- Fix service fetching to use billing_method instead of deprecated service_type
- Use leftJoin for optional relationships in task queries

refactor(time-sheets): polish time sheet UI and fix dependency warnings

---

server/src/components/billing-dashboard/FixedPlanServicesList.tsx
server/src/components/billing-dashboard/billing-plans/GenericPlanServicesList.tsx
server/src/components/companies/CompanyDetails.tsx
server/src/components/contacts/CompanyContactsList.tsx
server/src/components/time-management/approvals/ManagerApprovalDashboard.tsx
server/src/interfaces/billing.interfaces.ts
server/src/lib/models/service.ts
server/src/types/ui-reflection/UIStateContext.tsx

- time approval should close drawer
- fix billing tabs
- quiet logging

refactor: improve UI components and enhance user experience

---

server/src/components/billing-dashboard/AutomaticInvoices.tsx
server/src/components/billing-dashboard/BillingPlans.tsx
server/src/components/billing-dashboard/LineItem.tsx
server/src/components/billing-dashboard/ManualInvoices.tsx
server/src/components/billing-dashboard/billing-plans/BillingPlansOverview.tsx
server/src/components/billing-dashboard/plan-bundles/PlanBundleHeader.tsx
server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/BillingPlans.tsx
server/src/components/companies/PlanPickerDialog.tsx
server/src/components/ui/Tooltip.tsx
server/src/lib/actions/billingPlanAction.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/actions/manualInvoiceActions.ts
server/src/lib/billing/billingEngine.ts

fix(billing): clarify category requirement in plan creation UI
- Make it clear that leaving category unselected applies plan to all categories
- Update UI validation in PlanPickerDialog to reflect optional category
fix(invoices): resolve Temporal.PlainDate serialization in preview
- Convert Temporal.PlainDate to ISO8601 strings in previewInvoice action
- Ensure Next.js client components receive plain objects
fix(ui): correct button label in Generate Invoices tab
- Change "Finalize Selected Invoices" to "Generate Invoices"
- Reflect actual action being performed
fix(tooltips): resolve z-index conflict in billing cycle warnings
- Refactor CustomTooltip component using Radix
- Ensure proper visibility in DataTable context
fix(billing-plans): improve delete/remove plan messaging
- Replace …

fix(billing-ui): resolve misc issues in plans, invoices, and tooltips

---

package.json
server/src/app/msp/billing/credits/page.tsx
server/src/components/billing-dashboard/CreditManagement.tsx
server/src/components/billing-dashboard/CreditReconciliation.tsx
server/src/components/billing-dashboard/InvoiceTemplates.tsx
server/src/components/billing-dashboard/Invoices.tsx
server/src/components/billing-dashboard/ServiceCatalogManager.tsx
server/src/components/billing-dashboard/TaxRates.tsx
server/src/components/billing-dashboard/UsageTracking.tsx
server/src/components/companies/CompanyTaxRates.tsx
server/src/components/companies/ServiceCatalog.tsx
server/src/components/settings/api/AdminApiKeysSetup.tsx
server/src/components/settings/api/ApiKeysSetup.tsx
server/src/components/settings/general/InteractionTypeSettings.tsx
server/src/components/settings/general/TicketingSettings.tsx
server/src/components/settings/general/UserList.tsx
server/src/components/settings/policy/UserRoleAssignment.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/time-management/approvals/ManagerApprovalDashboard.tsx
server/src/components/time-management/time-entry/TimePeriodList.tsx
server/src/components/ui/DataTable.tsx
server/src/components/user-activities/ActivityActionMenu.tsx

This PR adds responsive behavior to the DataTable component, automatically collapsing and hiding columns when the browser size is too small to display the entire datatable at full width.
- Added a resize event listener to detect browser width changes
- Implemented logic to calculate which columns should be visible based on available space
- Added a visual indicator to show when columns are hidden
- Updated the UI reflection system to include information about hidden columns
- Prioritized columns based on importance (ID columns and columns with explicit width are prioritized)
1. Open any page with a DataTable component
2. Resize the browser window to make it narrower
3. Observe how columns automatically collapse and hide as the window gets smaller
4. Notice the blue notification banner …

Add responsive column handling to DataTable component

---

server/src/components/companies/BillingConfiguration.tsx
server/src/components/companies/PlanPickerDialog.tsx
server/src/lib/actions/companyBillingPlanActions.ts
server/src/lib/actions/invoiceActions.ts
server/src/lib/billing/billingEngine.ts

- Fixed proration logic in billingEngine.ts for mid-month end dates (Test 2.3)
- Corrected tax allocation calculation for mixed taxable/non-taxable services (Test 3.1)
- Fixed database error in editCompanyBillingPlan action for empty service_category (Test 2.3)
- Updated invoice preview tax calculation in invoiceActions.ts (Test 3.1)
- Added validation for negative/empty base rates in FixedPlanConfiguration.tsx (Test 8.1)
- Implemented proper handling for zero-value fixed fee plans (Test 1.1)

fix(billing): Fixed fee invoicing edge cases and validation

---

server/src/components/projects/DuplicateTaskDialog.tsx
server/src/components/projects/KanbanBoard.tsx
server/src/components/projects/MoveTaskDialog.tsx
server/src/components/projects/PhaseListItem.tsx
server/src/components/projects/ProjectDetail.tsx
server/src/components/projects/ProjectPhases.tsx
server/src/components/projects/ProjectQuickAdd.tsx
server/src/components/projects/StatusColumn.tsx
server/src/components/projects/TaskCard.tsx
server/src/components/projects/TaskForm.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/lib/actions/project-actions/projectTaskActions.ts
server/src/lib/models/projectTask.ts

🧙‍♂️✨🚀 May your tasks duplicate like rabbits (but in a controlled, manageable way)! 🐇💥🎉

Project phase fixes

---

server/src/components/companies/CompanyBundleDialog.tsx
server/src/lib/actions/companyPlanBundleActions.ts
server/src/lib/models/companyPlanBundle.ts

Improves company bundle management with date validation, improved date comparison logic, and UI enhancements including:
- Replace Checkbox with SwitchWithLabel for better UX in the bundle dialog
- Add validation preventing changes to dates that overlap with already invoiced periods
- Fix date overlap detection logic with clearer, more accurate conditions
- Improve error handling with more descriptive user feedback
- Make bundle assignment function async with proper error handling
- Add safer date initialization with proper type checking
- Optimize database query patterns for better performance
- Implement Temporal API for more reliable date comparisons
- Improve UI feedback when backend operations fail
The changes ensure data integrity when modifying company bundle dates and provide a …

feat(company-bundles): enhance date validation and UI components

---

server/src/components/client-portal/settings/CompanyDetailsSettings.tsx
server/src/components/companies/CompaniesList.tsx
server/src/components/companies/CompanyDetails.tsx
server/src/components/companies/CompanyGridCard.tsx
server/src/lib/actions/document-actions/documentActions.ts

Added loading spinners and icons to logo upload/delete buttons in CompanyDetails and CompanyDetailsSettings Restructured logo upload controls layout for better UX Added image preview support for image files in documentActions Made company names clickable links in CompaniesList and CompanyGridCard Added initial data fetch in CompanyDetails useEffect Impacts:
Better visual feedback during logo uploads/deletes Improved document preview capabilities
More intuitive navigation to company details
"Off with their logos!" cried the Red Queen, as the upload spinners twirled madly like the Mad Hatter's tea party 🎩☕🃏

Improved company logo upload UI and document preview handling

---

server/migrations/20250411000000_add_account_manager_id_to_companies.cjs
server/migrations/20250413142134_add_tax_rate_id_to_service_catalog.cjs
server/src/components/billing-dashboard/QuickAddService.tsx
server/src/components/billing-dashboard/TaxRates.tsx
server/src/lib/actions/taxRateActions.ts
server/src/lib/actions/user-actions/userActions.ts

Added confirmation dialog for tax rate deletion showing affected services Enhanced tax rate deletion logic to handle service dependencies Updated QuickAddService UI to use consistent Label components Simplified foreign key constraints in migrations
Added account manager validation in user deletion
Improved error handling throughout tax rate operations These changes impact billing and tax calculations by ensuring tax rate changes are properly validated and communicated to users. The UI updates provide more consistent form labeling.
"Off with their tax rates!" cried the Red Queen, but only after careful consideration of all affected services. 🎩♠️

CitusDB compatibility

---

server/src/components/settings/general/TicketingSettings.tsx
server/src/lib/actions/channel-actions/channelActions.ts

Added proper error handling for channel deletion with foreign key constraints Enhanced error messages in channel actions to provide more specific feedback Added success/error toast notifications in TicketingSettings component Improved default channel update logic with better error propagation Added null check for channel deletion to prevent errors These changes make channel management more robust by properly handling edge cases and providing better user feedback.
There's no place like a properly handled error state! 🏡✨

Improved channel deletion and error handling

---

server/migrations/20250430170700_add_dispatcher_role.cjs
server/src/app/api/auth/[...nextauth]/options.ts
server/src/components/technician-dispatch/DailyTechnicianScheduleGrid.tsx
server/src/components/technician-dispatch/ScheduleViewPanel.tsx
server/src/components/technician-dispatch/TechnicianDispatchDashboard.tsx
server/src/components/technician-dispatch/WeeklyTechnicianScheduleGrid.tsx
server/src/components/technician-dispatch/WorkItemListPanel.tsx
server/src/lib/actions/permissionActions.ts
server/src/lib/actions/workItemActions.ts
server/src/lib/auth/rbac.ts
server/src/lib/models/user.tsx

The dispatch board now obeys the Three Laws of Robotics: 1) No unauthorized UI shall harm users, 2) It must obey permission checks (except where such checks would conflict with the First Law), and 3) It must protect its own existence unless such protection would violate the First or Second Laws. 🤖⚡🔐

Dispatch schedule permissions

---

server/src/components/automation-hub/EventsCatalog.tsx
server/src/components/automation-hub/TemplateLibrary.tsx
server/src/components/automation-hub/Workflows.tsx
server/src/components/events-catalog/EventTriggerDialog.tsx
server/src/components/workflow-editor/WorkflowEditor.tsx
server/src/components/workflow-editor/WorkflowEditorComponent.tsx
server/src/components/workflow-editor/WorkflowVersionsDialog.tsx
server/src/lib/actions/workflow-editor-actions.ts
server/src/lib/actions/workflow-visualization-actions.ts
server/src/models/eventCatalog.ts
server/src/models/workflowEventAttachment.ts
shared/workflow/types/eventCatalog.ts

This update improves the user experience and functionality of the automation hub components, focusing on event catalog display, workflow management, and template library features.
- Display workflow name and version in event attachments for better identification
- Improve badge styling for active/inactive and system-managed workflows
- Add support for retrieving system events alongside tenant events
- Enhance UI for workflow listings with better styling and interaction
- Add workflow versioning capabilities with a dedicated dialog
- Implement row-level click for editing workflows
- Improve workflow status toggling with appropriate visual feedback
- Update query structure to properly retrieve workflow information from both tenant and system databases
- Add "Coming Soon" overlay for …

feat: Enhanced Event Catalog and Workflow Management

---

server/src/components/documents/Documents.tsx
server/src/components/schedule/TechnicianSidebar.tsx
server/src/components/time-management/time-entry/time-sheet/TimeEntryDialog.tsx
server/src/components/time-management/time-entry/time-sheet/TimeEntryEditForm.tsx
server/src/components/time-management/time-entry/time-sheet/TimeSheet.tsx
server/src/lib/actions/workItemActions.ts

Added automatic time entry creation for ad-hoc work items with zero billable duration Modified Documents component to reset creation state when selecting existing docs Enhanced TechnicianSidebar with rounded borders
Simplified TimeEntryEditForm by removing unused tax region logic Updated work item search to include ad-hoc items in all contexts Added scheduled times to work item data structure
Impacts:
Changes time entry validation for ad-hoc items
Modifies work item search behavior
Updates UI components with styling improvements
"Now your ad hoc time entries flow like a river of chocolate in Wonka's factory! 🍫🌊"

Implemented ad-hoc work item time entry automation and UI improvements:

---

server/src/components/companies/CompaniesList.tsx
server/src/components/contacts/Contacts.tsx
server/src/components/projects/Projects.tsx
server/src/components/settings/general/TicketingSettings.tsx
server/src/components/tickets/TicketingDashboard.tsx
server/src/components/ui/ConfirmationDialog.tsx
server/src/components/ui/Dialog.tsx
server/src/lib/actions/ticket-actions/ticketActions.ts

- Standardized confirmation dialogs using ConfirmationDialog component
- Improved dropdown menu implementations with better accessibility
- Added error handling for delete operations
- Enhanced keyboard navigation in dialogs
- Consolidated delete confirmation logic in TicketingSettings
Impacts:
- More consistent UI/UX for destructive actions
- Better accessibility with proper focus management
- Reduced code duplication for confirmation flows
- More robust error handling for delete operations
"These confirmations are more reliable than a robot butler's tea service - 'Would you like sugar with your deletion, sir?' 🤖☕"

Refactor confirmation dialogs and dropdown menus across components

---

server/src/components/tickets/TicketConversation.tsx

This PR changes the label from "Client Visible" to "Client" in the ticket detail screen as requested.

Change Client Visible to Client in ticket detail screen

---

tools/ai-automation/README.md
tools/ai-automation/docs/getting-started.md

This PR provides a comprehensive overhaul of the AI automation platform documentation to reflect the significant enhancements made in recent releases. The documentation now accurately covers the advanced browser session management, enhanced AI integration, and sophisticated automation capabilities.
- **Rebranded** from "AI Automation Tool" to "AI Automation Platform"
- **Browser Session Management**: Complete documentation for seamless headless/headed mode switching
- **Enhanced AI Integration**: Details on tool-aware AI system with codebase analysis capabilities
- **Advanced API Endpoints**: New session management APIs (`/api/browser/pop-out`, `/api/browser/pop-in`, `/api/browser/status`)
- **Comprehensive Tool System**: Documentation for 9+ AI tools (file operations, UI analysis, …

docs: comprehensive update of AI automation platform documentation

---

server/src/lib/init/serverInit.ts
server/src/middleware.ts

- Added explicit .env file loading in serverInit.ts using dotenv
- Removed redundant serverInit import from middleware.ts
- Ensures environment variables are loaded before validation
Beware the flying monkeys of circular dependencies! With this commit, we've oiled the tin man's joints and given the scarecrow a brain full of env vars. The wicked witch of bad initialization is melted! 🦁🎩🌪️✨

Refactor server initialization and env loading

---

server/src/lib/auth/ee.ts
server/src/lib/initializeApp.ts
server/src/lib/workflow/visualization/WorkflowComponentLoader.ts

should resolve docker image errors

fix for dynamic imports

---

cli/main.nu

- Refactor development environment management to use branch names instead of PR numbers for better flexibility
- Add comprehensive AI automation support with VNC visualization for Kubernetes environments
- Implement robust build system improvements with timestamp tracking and better Docker image management

feat: comprehensive dev environment and AI automation improvements

---

server/src/components/tickets/ticket/TicketDetails.tsx
server/src/components/tickets/ticket/TicketDocumentsSection.tsx

- Added wrapper divs around TicketInfo and TicketConversation components
- Simplified TicketDocumentsSection markup and styling
- Added data-automation-id and card styling to documents section
- Improved component organization and spacing consistency
You can unsee the messy markup now - the components have been properly dressed! 👔✨

- Restructured TicketDetails layout with consistent spacing using mb-6

---

.dockerignore
ee/server/Dockerfile
ee/server/Dockerfile.local
ee/server/Dockerfile.prod
ee/server/setup/create_database.js
server/Dockerfile
server/entrypoint.sh
server/migrations/20250606174000_update_priorities_table_structure.cjs

- Improve CitusDB compatibility by removing RLS policies 
- Refactor Dockerfile to improve package installation and caching efficiency
- Add local artifact containerization support
- Update priorities migration to use parameterized timestamp
- Enhance database setup script with async stack traces and additional checks
- Use local build for server artifacts instead of container build
- Enable email configuration for development environments

Improve CitusDB compatibility and container builds

---

tools/ai-automation/README.md
tools/ai-automation/src/index.ts

- Add null/undefined check for pageState in UI_STATE_UPDATE handler to prevent crashes
- Update Docker build commands with platform specification for cross-platform compatibility
- Fix container registry references in README

fix: prevent crashes in AI automation coding environments

---

server/migrations/20250627234131_add_order_to_service_types.cjs
server/migrations/20250629032631_add_columns_to_interaction_types.cjs

Migration 07 07

---

server/src/components/settings/policy/PermissionsMatrix.tsx

- Add ability to view permissions by resource (shows all roles that have access)
- Allow users to select both role and resource dropdowns simultaneously
- Support flexible viewing: by role only, by resource only, or both
- Enable permission editing from both role and resource perspectives
- Add "All Roles" option to view resource access across all roles
- Improve TypeScript types with new RolePermissionRow interface
- Simplify UI by removing separate view mode toggle
Now admins can tumble down the permissions rabbit hole from any angle they fancy,
just like Alice choosing which side of the mushroom to nibble! 🍄

feat: enhance permissions matrix with dual-mode viewing

---

server/src/app/msp/companies/[id]/page.tsx
server/src/components/companies/Companies.tsx
server/src/components/companies/QuickAddCompany.tsx

- Replace useToast hook with react-hot-toast for consistent notifications
- Add success toasts for company creation, deletion, and status updates
- Fix company list not refreshing after add/delete by using refreshKey state
- Prevent creating default location with only phone country code (+1)
- Improve error handling for deleted companies in detail view
- Remove redundant not-found page, use Next.js error boundaries
Now companies vanish properly like the Cheshire Cat, leaving only their success toast grin behind! 🐱✨

  fix: improve company management UX and fix deletion issues

---

server/src/components/TaxSettingsForm.tsx
server/src/components/settings/policy/UserRoleAssignment.tsx

when switched to dark mode, now see this

Buttons colors

---

server/src/components/client-portal/settings/ClientUserDetails.tsx
server/src/components/client-portal/settings/UserManagementSettings.tsx
server/src/components/settings/general/UserDetails.tsx
server/src/components/settings/general/UserManagement.tsx
server/src/components/settings/policy/PermissionsMatrix.tsx
server/src/components/settings/policy/RoleManagement.tsx
server/src/components/settings/policy/UserRoleAssignment.tsx
server/src/components/settings/security/SecuritySettingsPage.tsx
server/src/lib/actions/client-portal-actions/clientUserActions.ts
server/src/lib/actions/policyActions.ts
server/src/lib/actions/user-actions/userActions.ts

- Added role assignment functionality to ClientUserDetails component
- Extended UserManagementSettings with role selection for new users
- Implemented role filtering (MSP vs client portal) across user management
- Added role validation in user creation flows
- Improved role sorting and display in UI components
- Removed redundant security tab from SecuritySettingsPage
Impacts:
- Requires role data migration for existing client users
- Changes permission checking for role management
- Affects all client portal user creation and management flows
And with a click of my ruby slippers, may your roles always be properly assigned and your permissions never misaligned! 🏰✨

Enhanced client portal role management system 🧙‍♂️

---

server/src/app/msp/onboarding/layout.tsx
server/src/components/onboarding/steps/AddClientStep.tsx
server/src/components/onboarding/steps/BillingSetupStep.tsx
server/src/components/onboarding/steps/ClientContactStep.tsx
server/src/components/onboarding/steps/TeamMembersStep.tsx
server/src/components/onboarding/steps/TicketingConfigStep.tsx
server/src/lib/actions/onboarding-actions/onboardingActions.ts
server/src/lib/actions/referenceDataActions.ts

- Implemented react-hot-toast for user feedback across onboarding components
- Added delete capability for boards, categories, statuses and priorities in ticketing config
- Enhanced service type management with delete and duplicate prevention
- Improved UI consistency by standardizing info/note boxes to blue theme
- Added order number validation to prevent duplicates
- Fixed contact role field mapping in client contact step
Impacts:
- Requires react-hot-toast dependency
- Adds new API endpoints for reference data deletion
- Changes UI styling for info boxes
- Improves data integrity with duplicate prevention
"And with a flick of the Mad Hatter's wand, the boards and priorities vanished like Cheshire cats, leaving only toast crumbs as evidence of their existence!" 🎩🍞🐇

Added toast notifications and delete functionality for onboarding steps

---

ee/temporal-workflows/src/activities/checkout-session-activities.ts
ee/temporal-workflows/src/config/startupValidation.ts
ee/temporal-workflows/src/worker.ts
helm/templates/deployment.yaml
shared/core/VaultSecretProvider.ts

- Add comprehensive startup validation for temporal-worker
- Integrate with Vault for secret management
- Remove insecure fallback values
- Replace `INTERNAL_API_SHARED_SECRET` with `ALGA_AUTH_KEY` 
- Remove insecure 'temp-secret' fallback - now throws exception if auth key is missing
- Add startup validation system following the pattern from `initializeApp.ts`:
- Validates required configuration (ALGA_AUTH_KEY, database credentials, Temporal settings)
- Validates optional configuration with sensible defaults
- Tests database connectivity before starting
- Tests Temporal connectivity before starting
- Logs configuration with sensitive values masked
- Now requires `VAULT_APP_SECRET_PATH` and `VAULT_TENANT_SECRET_PATH_TEMPLATE` to be explicitly set
- No more default paths - throws …

feat: Add startup validation and Vault integration for temporal-worker

---

ee/temporal-workflows/src/activities/email-activities.ts
ee/temporal-workflows/src/config/startupValidation.ts
ee/temporal-workflows/src/types/workflow-types.ts

- Updated welcome email template with Alga PSA branding and improved visual design
- Enhanced messaging to highlight key value propositions of the platform
- Ensured consistent branding throughout the email template
- **Brand Identity**: Changed from generic branding to specific Alga PSA branding
- **Color Scheme**: Updated to use Alga PSA purple (#8a4dea) as the primary color
- **Typography**: Updated fonts to Inter and Poppins for better readability
- **Messaging**: Added value proposition messaging: "Say goodbye to scattered tools, manual workarounds, and overly complex systems"
- **Configuration**: Added APPLICATION_URL as a required configuration for proper login URL generation
- **Code Cleanup**: Removed unused loginUrl parameter from workflow types

feat: improve welcome email branding for Alga PSA

---

Dockerfile.build
ee/server/Dockerfile.build
ee/server/migrations/20250810140000_align_registry_v2_schema.cjs
ee/server/src/components/GmailProviderForm.tsx
helm/templates/deployment.yaml
helm/values.yaml
server/src/app/api/auth/google/callback/route.ts
server/src/app/api/auth/microsoft/callback/route.ts
server/src/app/api/email/oauth/initiate/route.ts
server/src/components/EmailProviderSelector.tsx
server/src/components/GmailProviderForm.tsx
server/src/components/admin/EmailSettings.tsx
server/src/components/providers/gmail/BasicConfigCard.tsx
server/src/components/providers/gmail/OAuthSection.tsx
server/src/components/providers/gmail/ProcessingSettingsCard.tsx
server/src/components/providers/gmail/schemas.ts
server/src/components/providers/gmail/useOAuthPopup.ts
server/src/lib/actions/email-actions/emailProviderActions.ts
server/src/utils/email/oauthHelpers.ts

Title: Inbound email config + deployment fixes (OAuth/Helm); align registry v2 migrations
Summary
- Introduces inbound email configuration improvements and sets the default Email Settings tab to Inbound.
- Refactors Gmail OAuth flow to use server actions, avoids pre-auth automation until tokens are present, and adds a shared OAuth popup hook and provider components.
- Unifies OAuth env var naming (GOOGLE_*/MICROSOFT_*) and removes EE_* usages; adds hosted detection via server-side NEXTAUTH_URL.
- Updates Helm values and deployment manifests to surface Gmail integration configuration.
- Fixes and aligns Postgres migrations for registry v2 and JSONB backfills; resolves PK constraint conflicts and constraint renames.
- Minor Dockerfile tweaks for build consistency (EE and OSS).
Key Changes
- …

Inbound email config + deployment fixes (OAuth/Helm); align registry v2 migrations

---

server/src/components/companies/CompanyPicker.tsx
server/src/components/contacts/ContactDetails.tsx
server/src/components/contacts/ContactDetailsView.tsx
server/src/components/settings/general/UserDetails.tsx
server/src/components/settings/general/UserManagement.tsx
server/src/lib/actions/contact-actions/contactActions.tsx
server/src/lib/actions/user-actions/userActions.ts

- Added "None" option to CompanyPicker component for clearing company associations
- Implemented company editing UI in ContactDetails and ContactDetailsView
- Improved UserManagement with client portal support and company selection
- Added getClientPortalRoles function to userActions
- Updated contactActions to handle null company_id
- Enhanced user creation flow with type-specific role validation
Impacts:
- Allows clearing company associations from contacts
- Enables proper client portal user management
- Adds role type validation during user creation
- Improves user experience for company assignment
Follow the yellow brick road of company associations, for there's no place like a well-organized contact management system! 🧙‍♂️🏢

Enhanced company association and user management features

---

server/src/lib/models/interactions.ts

Before, editing interaction would not save, nothing would happen when updating the interaction button.

Fixed non working "update interaction" button

---

server/src/lib/actions/time-period-settings-actions/timePeriodSettingsActions.ts

Adds missing tenant isolation to time period settings actions

Fix: Add missing tenant isolation to time period settings actions

---

ee/server/package.json
ee/server/src/components/settings/extensions/InstallerPanel.tsx
ee/server/src/lib/actions/extBundleActions.ts
helm/templates/deployment-dev.yaml
helm/templates/deployment.yaml
helm/values-dev-env.yaml
helm/values.yaml
package.json
server/index.ts
server/package.json
server/src/lib/analytics/analyticsSettings.ts
server/src/lib/analytics/posthog.ts
server/src/lib/observability/index.ts
server/src/lib/observability/initialization.ts
server/src/lib/observability/logging.ts
server/src/lib/telemetry/initialization.ts

- merge release/0.10.0 into main to bring the release fixes and version updates back to main
- not run

Merge release/0.10.0 into main

---

server/src/services/email/providers/MicrosoftGraphAdapter.ts

- merge release/0.10.0 changes back into main for synchronization
- not run (merge-only change)

Merge release/0.10.0 back into main

---

cli/hosted-env.nu

This PR updates the hosted-env.nu configuration file with necessary changes.

Update hosted-env.nu configuration
